---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zigbee2mqtt-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: "{{ .zigbee2mqtt_config_advanced_ext_pan_id }}"
        ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: "{{ .zigbee2mqtt_config_advanced_pan_id }}"
        ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: "{{ .zigbee2mqtt_config_advanced_network_key }}"
        # Mosquitto
        ZIGBEE2MQTT_CONFIG_MQTT_USER: "{{ .mosquitto_zigbee2mqtt_username }}"
        ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: "{{ .mosquitto_zigbee2mqtt_password }}"
  dataFrom:
    - extract:
        key: zigbee2mqtt
      rewrite:
        - regexp:
            source: "(.*)"
            target: "zigbee2mqtt_$1"
    - extract:
        key: mosquitto
      rewrite:
        - regexp:
            source: "(.*)"
            target: "mosquitto_$1"
