---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dsmr-reader
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: kireque
        namespace: flux-system

  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/xirixiz/dsmr-reader-docker
      tag: 5.10.3-2023.04.02

    enableServiceLinks: false

    env:
      DJANGO_TIME_ZONE: "Europe/Amsterdam"
      DSMRREADER_REMOTE_DATALOGGER_INPUT_METHOD: ipv4
      DSMRREADER_REMOTE_DATALOGGER_NETWORK_HOST: "10.1.3.45"
      DSMRREADER_REMOTE_DATALOGGER_NETWORK_PORT: "8088"

      DJANGO_DATABASE_HOST:
        valueFrom:
          secretKeyRef:
            name: database-dsmr-reader-user
            key: HOST
      DJANGO_DATABASE_PORT: "5432"
      DJANGO_DATABASE_USER:
        valueFrom:
          secretKeyRef:
            name: database-dsmr-reader-user
            key: LOGIN
      DJANGO_DATABASE_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: database-dsmr-reader-user
            key: PASSWORD
      DJANGO_DATABASE_NAME:
        valueFrom:
          secretKeyRef:
            name: database-dsmr-reader-user
            key: DATABASE_NAME

    envFrom:
      - secretRef:
          name: dsmr-reader-secret

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        ingressClassName: "internal-nginx"
        hosts:
          - host: &host "dsmr-reader.econline.local"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    resources:
      requests:
        cpu: 47m
        memory: 662M
      limits:
        memory: 662M
