---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: watchstate
spec:
  components:
    - ../../../../components/kopiur/adopt-static
    - ../../../../components/kopiur/backup
    - ../../../../components/nfs-scaler
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/media/watchstate/app
  postBuild:
    substitute:
      APP: watchstate
      KOPIUR_VOLUMENAME: pvc-a46e4758-b735-4e4f-81da-25c6064124c6
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
