CLUSTER_NAME: ENC[AES256_GCM,data:JgSJbFzCcePgYw==,iv:Hv8tYlkg1zbUlvnU6u+g8MZGDX1PbENJ5BoblQU6eSs=,tag:0Yo1iX4II7JO0yOXhORx+A==,type:str]
EXTERNAL_CLUSTER_NAME: ENC[AES256_GCM,data:UdianXoH0P1e+g==,iv:U+cURyKZEnGlggvS0WEoO7mtmRr6D/32tW7OYKMSufU=,tag:bLmvJDwd2UESefW5lIk48w==,type:str]
CLUSTER_ENDPOINT_IP: ENC[AES256_GCM,data:DYZKdlE+h01+/Jax,iv:IQ70CVlZtXOEov8ZqYoY919VpGaUm8yYaeIIRREm5Fw=,tag:iHaZyGy2uTPrajNXCORrtg==,type:str]
INTERNAL_DOMAIN: ENC[AES256_GCM,data:I13M/uPubPkBA8H23AY=,iv:YZwfQd5xW45Lkf8pu4MyucjhMkt6gmKT1M8FGSeD1YU=,tag:3usUDIEj0xaGPg6RGdwq2Q==,type:str]
EXTERNAL_DOMAIN: ENC[AES256_GCM,data:IymhkmDgIbYF/xw=,iv:thq3eP/WoBmvotckwPxqWRyUOR/MXX/c33nGLCcR4tc=,tag:zaj8ot4PWtYk4F8FgMZIcQ==,type:str]
DNS_SERVER: ENC[AES256_GCM,data:k5FOYe32o3cjnO4=,iv:F2Lj9b2Ukto2nCbB6XB5ut1Y1e0+VgSeIhDlEKSX2tE=,tag:doDGQQtQfHdETfurCYIffg==,type:str]
NTP_SERVER: ENC[AES256_GCM,data:aP/tt/sY6fit6Bg=,iv:QqVOMzgef/cZw0IiflutJfCdBbbPjbVWjV3dy2RtRoQ=,tag:lo92f73G++yMAZR+uG0NOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vq46r6697jer0udz6pjx9grgt5xlpg70wjvnw3l6pjmup4k57e4qnqn7vn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIS3hTRFZnUU5zNTRVZmFs
            L1h0bStUNE1SVVhzTmhwTHhHNE5kM0xBN1NjCjNnbjIxL1RmYXQzQkpHVytiNXd5
            OGhUMjMvdm9KQlFpRnQvN0gxMWpEeVkKLS0tIGQwcW4vWHNzblVHNkQ2UXBQZVhB
            TElyTmdHVDJMK0oxS0lGTTNCZlNPV0EKFg96T/ldUW6GBAXffmhbCT0WD0t10E1B
            mGkiw6GvFSNrs+mT8WQ/d4Xg6VscYkQe3KWCnUqVcT4h8pkLap/29A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-17T20:36:17Z"
    mac: ENC[AES256_GCM,data:IphFodDB3LxXFzpP3K6PbnGzUa48KSM33k828ak9Xs/CqhNz7nIWwBfQREem5/jW+JG2m/Uwi8u6lPyEXnMZNaPsR9o9gwUrZFxAE97OOCQ1JGkXdyZ//n3PGC4xiTaTHl+HgKSuPbQ13uFzQyWkewh27b4ACksOTlMchyHcTkU=,iv:b3frmzo9GlcJa50n3wlR+gpvoXw3rRlcN7sEat7ZLiQ=,tag:9F8YqvOI6zSQTm+x0sY9rQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
