---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-prowlarr
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/downloads/prowlarr/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false # no flux ks dependents
  dependsOn:
    - name: cluster-apps-rook-ceph-cluster