---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/onedr0p/prowlarr-nightly
      tag: 1.9.0.3964@sha256:7cd75c3694d323a81ebc51d3656569fc05a6d58d6d5fc577756f875256fe97ab

    env:
      PROWLARR__INSTANCE_NAME: Prowlarr
      PROWLARR__PORT: &port 9696
      PROWLARR__LOG_LEVEL: info
      PROWLARR__ANALYTICS_ENABLED: "False"
      PROWLARR__AUTHENTICATION_METHOD: External
      PROWLARR__API_KEY: testtesttesttesttest

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
        annotations:
          hajimari.io/icon: mdi:prowlarr
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads
          gethomepage.dev/icon: "prowlarr"
          gethomepage.dev/name: "Prowlarr"
          gethomepage.dev/widget.type: "prowlarr"
          gethomepage.dev/widget.url: "http://prowlarr.downloads.svc.cluster.local:9696"
          gethomepage.dev/widget.key: "testtesttesttesttest"
          gethomepage.dev/podSelector: ""

    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config

    resources:
      requests:
        cpu: 18m
        memory: 128Mi
      limits:
        memory: 256Mi

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
