---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-snapshot-controller
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/system-controller/snapshot-controller/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  timeout: 2m