---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: openclaw-secret
    template:
      data:
        OPENAI_API_KEY: "{{ .AZURE_OPENAI_API_KEY }}"
        OPENAI_BASE_URL: "{{ .OPENAI_BASE_URL }}"
        OPENCLAW_GATEWAY_TOKEN: "{{ .OPENCLAW_GATEWAY_TOKEN }}"
  dataFrom:
    - extract:
        key: openclaw
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: openclaw-config
    template:
      templateFrom:
        - configMap:
            name: openclaw-config-template
            items:
              - key: openclaw.json
  dataFrom:
    - extract:
        key: openclaw
