---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-reloader
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/system/reloader/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  dependsOn:
    - name: cluster-apps-snapshot-controller
  wait: false # no flux ks dependents