---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./pvc.yaml
commonLabels:
  app.kubernetes.io/name: radarr
  app.kubernetes.io/instance: radarr