---
- name: Install Python docker packages
  ansible.builtin.pip:
    name:
      - docker==5.0.3

# Manage certificates
- name: Manage certificates
  block:
    - name: "Certificates : Manage syno-cli image"
      community.docker.docker_image:
        source: pull
        name: "{{ apps.syno_cli.image_repository }}:{{ apps.syno_cli.image_tag }}"

    - name: "Certificates : Manage certificate"
      include_tasks: certificates.yml
      loop: "{{ certificates }}"

# Manage applications
- import_tasks: minio.yml
  tags: minio
- import_tasks: node-exporter.yml
  tags: node-exporter
