---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blackbox-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: 9.4.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 30m
  values:
    fullnameOverride: blackbox-exporter

    image:
      registry: quay.io

    podSecurityContext:
      sysctls:
        - name: net.ipv4.ping_group_range
          value: "0 2147483647"

    config:
      modules:
        http_2xx:
          prober: http
          timeout: 5s
          http:
            valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
            follow_redirects: true
            preferred_ip_protocol: "ip4"
        icmp:
          prober: icmp
          timeout: 30s
          icmp:
            preferred_ip_protocol: "ip4"

    ingress:
      enabled: true
      className: internal-nginx
      hosts:
        - host: &host "blackbox-exporter.econline.nl"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

    prometheusRule:
      enabled: true
      additionalLabels:
        app: prometheus-operator
        release: prometheus
      rules:
        - alert: BlackboxSslCertificateWillExpireSoon
          expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 3
          for: 15m
          labels:
            severity: critical
          annotations:
            summary: |-
              The SSL certificate for {{ $labels.target }} will expire in less than 3 days
        - alert: BlackboxSslCertificateExpired
          expr: probe_ssl_earliest_cert_expiry - time() <= 0
          for: 15m
          labels:
            severity: critical
          annotations:
            summary: |-
              The SSL certificate for {{ $labels.target }} has expired
        - alert: BlackboxProbeFailed
          expr: probe_success == 0
          for: 15m
          labels:
            severity: critical
          annotations:
            summary: |-
              The host {{ $labels.instance }} is currently unreachable

    pspEnabled: false

    securityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        add: ["NET_RAW"]

    serviceMonitor:
      enabled: true
      defaults:
        labels:
          release: prometheus
        interval: 1m
        scrapeTimeout: 30s
      targets:
        # Robot vacuums
        - module: icmp
          name: valetudo-living-room-icmp
          url: living-vacuum.home.econline.nl
        - module: http_2xx
          name: valetudo-living-room-http
          url: living-vacuum.home.econline.nl

        # Other devices
        # - module: icmp
        #   name: zigbee-controller-icmp
        #   url: office-zigbee-adapter.home.econline.nl

        - module: icmp
          name: velux-gateway
          url: hallway-velux-gateway.home.econline.nl

        - module: icmp
          name: ping-cloudflare
          url: 1.1.1.1
          scrape_interval: 30s
