---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radicale
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radicale-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        users: |-
          bernd:{{ index . "radicale_bernd" }}
          man-yie:{{ index . "radicale_man-yie" }}
          family:{{ index . "radicale_family" }}
          eva:{{ index . "radicale_eva" }}
  dataFrom:
    - extract:
        key: radicale
      rewrite:
        - regexp:
            source: "(.*)"
            target: "radicale_$1"
