---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radicale
  namespace: selfhosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: kireque
        namespace: flux-system

  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/kireque/radicale
      tag: 3.1.8

    service:
      main:
        ports:
          http:
            port: 5232

    ingress:
      main:
        enabled: true
        ingressClassName: "external-nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-exteconline.local
        hosts:
          - host: &host "radicaleeconline.local"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: configMap
        name: radicale-configmap
        subPath: config.cfg
        mountPath: /config/config
        readOnly: true

      auth:
        enabled: true
        type: secret
        name: radicale-secret
        subPath: users
        mountPath: /config/users
        readOnly: true

    resources:
      requests:
        cpu: 21m
        memory: 192Mi
      limits:
        memory: 1024Mi

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"

    volumeClaimTemplates:
      - name: data
        mountPath: /data
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block
