---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  - ./volsync.yaml
commonLabels:
  app.kubernetes.io/name: radicale
  app.kubernetes.io/instance: radicale
configMapGenerator:
  - name: radicale-configmap
    files:
      - config/config.cfg
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
