---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate
spec:
  # refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: frigate-secret
    creationPolicy: Owner
    template:
      data:
        FRIGATE_DOORBELL_IP: doorbell.home.econline.nl
        FRIGATE_DOORBELL_USERNAME: "{{ .FRIGATE_DOORBELL_USERNAME }}"
        FRIGATE_DOORBELL_PASSWORD: "{{ .FRIGATE_DOORBELL_PASSWORD }}"
  dataFrom:
    - extract:
        key: frigate
      rewrite:
        - regexp:
            source: "(.*)"
            target: "FRIGATE_$1"

