---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: frigate
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      frigate:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          nodeSelector:
            # feature.node.kubernetes.io/custom-google-coral: "true"
            intel.feature.node.kubernetes.io/gpu: "true"

        containers:
          app:
            image:
              repository: ghcr.io/blakeblackshear/frigate
              tag: 0.16.1@sha256:cb6624b9075f76ece626139eedca7e728cab1456a5f8c351afbf877320826bc1
            env:
              LIBVA_DRIVER_NAME: i965
            envFrom:
              - secretRef:
                  name: frigate-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/version
                    port: &port 5000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 250m
                memory: 1Gi
              limits:
                memory: 4Gi
                gpu.intel.com/i915: 1
    service:
      app:
        ports:
          http:
            primary: true
            port: *port
          go2rtc:
            enabled: true
            port: &apiPort 1984
          rtsp:
            enabled: true
            port: 8554
    persistence:
      data:
        existingClaim: frigate-config
      config:
        type: configMap
        name: frigate-config
        globalMounts:
          - path: /config/config.yml
            subPath: config.yml
            readOnly: true
      cache:
        type: emptyDir
        medium: Memory
        sizeLimit: 2Gi
        globalMounts:
          - path: /dev/shm
      media:
        type: nfs
        server: nas.home.econline.nl
        path: /volume1/Apps/frigate
        globalMounts:
          - path: /media

    route:
      app:
        hostnames:
          - frigate.econline.nl
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port