---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-weave-gitops
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/flux-system/weave-gitops/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false # no flux ks dependents
  retryInterval: 1m
  timeout: 5m
