---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: thanos-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AZURE_STORAGE_ACCOUNT_NAME: "{{ .minio_storage_account_name }}"
        AZURE_STORAGE_ACCOUNT_KEY: "{{ .minio_storage_account_key }}"
        AZURE_CONTAINER: "{{ .minio_storage_account_container }}"
  dataFrom:
    - extract:
        key: Minio
      rewrite:
        - regexp:
            source: "(.*)"
            target: "minio_$1"