
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: thanos
spec:
  interval: 30m
  chart:
    spec:
      chart: thanos
      version: 15.0.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 30m
  values:
    objstoreConfig:
      type: azure

    query:
      enabled: true
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: monitoring
      stores:
        - thanos-storegateway.monitoring.svc.cluster.local:10901
      replicaLabels:
        - "__replica__" # must match with kube-prometheus-stack value `.prometheus.prometheusSpec.replicaExternalLabelName`
      resources:
        requests:
          cpu: 15m
          memory: 64M

    queryFrontend:
      enabled: true
      ingress:
        enabled: true
        hostname: "thanos.econline.nl"
        ingressClassName: "internal-nginx"
        tls: true

    bucketweb:
      enabled: true
      resources:
        requests:
          cpu: 15m
          memory: 64M

    compactor:
      enabled: true
      extraFlags:
        - "--compact.concurrency=4"
        - --delete-delay=30m
      retentionResolutionRaw: 14d
      retentionResolution5m: 30d
      retentionResolution1h: 90d
      resources:
        requests:
          cpu: 15m
          memory: 204M
      persistence:
        enabled: true
        storageClass: "openebs-hostpath"
        size: 15Gi

    storegateway:
      enabled: true
      resources:
        requests:
          cpu: 23m
          memory: 204M
      persistence:
        enabled: true
        storageClass: "openebs-hostpath"
        size: 1Gi

    ruler:
      enabled: true
      alertmanagers:
        - http://alertmanager.monitoring.svc.cluster.local:9093
      clusterName: ${CLUSTER_NAME} # must match with kube-prometheus-stack value `.prometheus.prometheusSpec.externalLabels.cluster`
      config: |-
        groups:
          - name: "PrometheusWatcher"
            rules:
              - alert: "PrometheusDown"
                expr: absent(up{job="kube-prometheus-stack-prometheus"})
      dnsDiscovery:
        enabled: true
      persistence:
        enabled: true
        storageClass: "openebs-hostpath"
        size: 512Mi
      resources:
        requests:
          cpu: 23m
          memory: 128M
        limits:
          memory: 256M

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  valuesFrom:
    - targetPath: objstoreConfig.config.container
      kind: Secret
      name: thanos-secret
      valuesKey: AZURE_CONTAINER
    - targetPath: objstoreConfig.config.storage_account
      kind: Secret
      name: thanos-secret
      valuesKey: AZURE_STORAGE_ACCOUNT_NAME
    - targetPath: objstoreConfig.config.storage_account_key
      kind: Secret
      name: thanos-secret
      valuesKey: AZURE_STORAGE_ACCOUNT_KEY
