---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cloudflared
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-externaldns-external
  path: "./kubernetes/main/apps/networking/cloudflared/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
