---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-navidrome-main
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/cluster-0/apps/media/navidrome/main"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-rook-ceph-cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-navidrome-kids
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/cluster-0/apps/media/navidrome/kids"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-rook-ceph-cluster
