---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scale-job-account
  namespace: scripts
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-scaler-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-scaler-rolebinding
subjects:
  - kind: ServiceAccount
    name: scale-job-account
    namespace: scripts
roleRef:
  kind: ClusterRole
  name: deployment-scaler-role
  apiGroup: rbac.authorization.k8s.io
