# yaml-language-server: $schema=http://frigate.econline.nl/api/config/schema.json
---
mqtt:
  host: mosquitto.database.svc.cluster.local

database:
  path: /data/frigate.db

detectors:
  ov:
    type: openvino
    device: AUTO

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

ffmpeg:
  global_args:
    - "-hide_banner"
    - "-loglevel"
    - "info"
  hwaccel_args: preset-intel-qsv-h264
  output_args:
    record: preset-record-generic-audio-aac

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: False

record:
  enabled: true
  retain:
    days: 1
    mode: all
  alerts:
    retain:
      days: 1
  detections:
    retain:
      days: 1
timestamp_style:
  format: '%d/%m/%Y %H:%M:%S'
  effect: solid

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 1

lpr:
  enabled: true
  device: GPU
  enhancement: 2

semantic_search:
  enabled: true
  reindex: false

objects:
  track:
    - person
    - pizza
    - knife

review:
  alerts:
    labels:
      - pizza
      - knife
  detections:
    labels:
      - person

go2rtc:
  streams:
    entrance_record:
      - rtsp://{FRIGATE_username}:{FRIGATE_password}@doorbell.home.econline.nl:554/
    entrance_detect:
      - rtsp://{FRIGATE_username}:{FRIGATE_password}@doorbell.home.econline.nl:554/h264Preview_01_sub

cameras:
  entrance:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/entrance_record
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/entrance_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
    zones:
      front_door:
        coordinates: 0,0,0.621,0,0.654,0.501,0.761,0.509,0.759,0.567,1,0.655,1,1,0,1
        objects:
          - person
  # entrance:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://go2rtc.home-automation.svc.cluster.local:554/entrance_record
  #         input_args: preset-rtsp-restream
  #         roles:
  #           - record
  #           - audio
  #       - path: rtsp://go2rtc.home-automation.svc.cluster.local:554/entrance_detect
  #         input_args: preset-rtsp-restream
  #         roles:
  #           - detect
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 10
