---
mqtt:
  host: vernemq.database.svc.cluster.local
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

# detectors:
#   openvino:
#     type: openvino
#     device: GPU

# model:
#   width: 300
#   height: 300
#   input_tensor: nhwc
#   input_pixel_format: bgr
#   labelmap_path: /openvino-model/coco_91cl_bkgr.txt
#   path: /openvino-model/ssdlite_mobilenet_v2.xml

ffmpeg:
  global_args:
    - "-hide_banner"
    - "-loglevel"
    - "info"
  hwaccel_args: preset-intel-qsv-h264
  output_args:
    record: preset-record-generic-audio-aac

# birdseye:
#   mode: motion

record:
  enabled: true
  retain:
    days: 5
    mode: motion

snapshots:
  enabled: true
  retain:
    default: 5
    objects:
      person: 30

objects:
  track:
    - person
    # - dog
    # - cat

cameras:
  entrance:
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc.home-automation.svc.cluster.local:554/entrance_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://go2rtc.home-automation.svc.cluster.local:554/entrance_record
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
    detect:
      width: 640
      height: 480
      fps: 10
    live:
      stream_name: entrance_record
