---
mqtt:
  host: emqx-listeners.database.svc.cluster.local
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'
database:
  path: /data/frigate.db
# detectors:
#   coral:
#     type: edgetpu
#     device: pci
ffmpeg:
  global_args: ["-hide_banner", "-loglevel", "info"]
  hwaccel_args: preset-intel-qsv-h264
  output_args:
    record: preset-record-generic-audio-aac
birdseye:
  mode: continuous
record:
  enabled: true
  retain:
    days: 5
    mode: motion
snapshots:
  enabled: true
  retain:
    default: 5
    objects:
      person: 30
objects:
  track:
    - person
    - dog
    - cat

go2rtc:
  streams:
    entrance_detect:
      - rtsp://frigate:frigate1234@doorbell.home.econline.nl:554/h264Preview_01_sub
    entrance_record:
      - rtsp://frigate:frigate1234@doorbell.home.econline.nl:554/h264Preview_01_main
      - "ffmpeg:entrance_record#audio=aac"

cameras:
  entrance:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/entrance_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/entrance_record
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      height: 480
      width: 704
      fps: 5
    objects:
      filters:
        person:
          min_area: 1500
          max_area: 100000
          threshold: 0.75
          min_score: 0.60
    live:
      stream_name: entrance_record


# cameras:
#   entrance:
#     ffmpeg:
#       inputs:
#         - path: rtsp://frigate:frigate1234@doorbell.home.econline.nl:554/h264Preview_01_sub
#           roles:
#             - detect
#         - path: rtsp://frigate:frigate1234@doorbell.home.econline.nl:554/h264Preview_01_main
#           roles:
#             - record
  # dining_room:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://go2rtc.home-automation.svc.cluster.local:554/dining_room_lq
  #         roles:
  #           - detect
  #       - path: rtsp://go2rtc.home-automation.svc.cluster.local:554/dining_room_hq
  #         roles:
  #           - record
  # living_room:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://go2rtc.home-automation.svc.cluster.local:554/living_room_lq
  #         roles:
  #           - detect
  #       - path: rtsp://go2rtc.home-automation.svc.cluster.local:554/living_room_hq
  #         roles:
  #           - record
  # office:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://go2rtc.home-automation.svc.cluster.local:554/office_lq
  #         roles:
  #           - detect
  #       - path: rtsp://go2rtc.home-automation.svc.cluster.local:554/office_hq
  #         roles:
  #           - record