[settings]
pipx_uvx = true

[env]
# Kubernetes
KUBECONFIG = '{{config_root}}/kubernetes/kubeconfig'
TALOSCONFIG = '{{config_root}}/kubernetes/talos/talosconfig'

[tools]
"aqua:astral-sh/uv" = ["latest"]
"pipx:flux-local" = ["latest"]
"talosctl" = ["1.11.0"]
"aqua:budimanjojo/talhelper" = ["latest"]
"aqua:google/yamlfmt" = ["latest"]
"aqua:casey/just" = ["latest"]
"aqua:charmbracelet/gum" = ["latest"]
