[settings]
pipx_uvx = true

[env]
# Kubernetes
KUBECONFIG = '{{config_root}}/kubernetes/kubeconfig'
TALOSCONFIG = '{{config_root}}/kubernetes/talos/clusterconfig/talosconfig'

[tools]
"aqua:astral-sh/uv" = ["latest"]
"pipx:flux-local" = ["latest"]
"talosctl" = ["latestw"]
"aqua:budimanjojo/talhelper" = ["latest"]