---
creation_rules:
  - path_regex: k8s/(global|clusters)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    # Personal, Flux
    age: >-
      age1vq46r6697jer0udz6pjx9grgt5xlpg70wjvnw3l6pjmup4k57e4qnqn7vn

  - path_regex: .*\.sops\.ya?ml
    # Personal
    age: >-
      age1vq46r6697jer0udz6pjx9grgt5xlpg70wjvnw3l6pjmup4k57e4qnqn7vn
