creation_rules:
    - path_regex: kubernetes/.*\.sops\.ya?ml
      encrypted_regex: ^(data|stringData)$
      key_groups:
        - age:
            - age1mtzvncgylzrqrf3m6e4wpxt8sk6zq59mdraehr7lhxksyltmwdksl0ltrv
    - path_regex: kubernetes/.*\.sops\.toml
      key_groups:
        - age:
            - age1mtzvncgylzrqrf3m6e4wpxt8sk6zq59mdraehr7lhxksyltmwdksl0ltrv
    - path_regex: ansible/.*\.sops\.ya?ml
      unencrypted_regex: ^(kind)$
      key_groups:
        - age:
            - age1mtzvncgylzrqrf3m6e4wpxt8sk6zq59mdraehr7lhxksyltmwdksl0ltrv
    - path_regex: .*\.sops\.ya?ml
      key_groups:
        - age:
            - age1mtzvncgylzrqrf3m6e4wpxt8sk6zq59mdraehr7lhxksyltmwdksl0ltrv
