---
creation_rules:
  - path_regex: k8s/(global|clusters)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    # Personal, Flux
    age: >-
      age180mw9nde354qyrklgcylwdn42ql657j6vcpdud5gqpeyp7e9v4xsrdns9t

  - path_regex: .*\.sops\.ya?ml
    # Personal
    age: >-
      age180mw9nde354qyrklgcylwdn42ql657j6vcpdud5gqpeyp7e9v4xsrdns9t
