---
creation_rules:
  - path_regex: k8s/(global|clusters)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    # Personal, Flux
    age: >-
      age1mtzvncgylzrqrf3m6e4wpxt8sk6zq59mdraehr7lhxksyltmwdksl0ltrv
  - path_regex: .*\.sops\.ya?ml
    # Personal
    age: >-
      age1mtzvncgylzrqrf3m6e4wpxt8sk6zq59mdraehr7lhxksyltmwdksl0ltrv