---
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  PROXMOX_DIR: "{{.PROJECT_DIR}}/infrastructure/proxmox"
  TALOS_DIR: "{{.PROJECT_DIR}}/infrastructure/talos"

includes:
  proxmox: .taskfiles/Proxmox/Tasks.yml
  talos: .taskfiles/Talos/Tasks.yml
  flux: .taskfiles/Flux/Tasks.yml
  # ku: .taskfiles/Kubernetes/Tasks.yml
  # vs: .taskfiles/VolSync/Tasks.yml

tasks:

  default:
    silent: true
    cmds: 
      - "task proxmox:redeploy"
      - "task talos:bootstrap"
      - "task flux:bootstrap" 
