---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: emqx-init-user
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: emqx-init-user-secret
    creationPolicy: Owner
    template:
      data:
        init-user.json: |
          [
            {"user_id": "{{ index . "username" }}", "password": "{{ index . "password" }}", "is_superuser": true},
            {"user_id": "{{ index . "user_mqtt_username" }}", "password": "{{ index . "user_mqtt_password" }}", "is_superuser": false},
            {"user_id": "{{ index . "dsmr_reader_username" }}", "password": "{{ index . "dsmr_reader_password" }}", "is_superuser": false},
            {"user_id": "{{ index . "esp_username" }}", "password": "{{ index . "esp_password" }}", "is_superuser": false},
            {"user_id": "{{ index . "home_assistant_username" }}", "password": "{{ index . "home_assistant_password" }}", "is_superuser": false},
            {"user_id": "{{ index . "zigbee2mqtt_exporter_username" }}", "password": "{{ index . "zigbee2mqtt_exporter_password" }}", "is_superuser": false},
            {"user_id": "{{ index . "zigbee2mqtt_username" }}", "password": "{{ index . "zigbee2mqtt_password" }}", "is_superuser": false},
            {"user_id": "{{ index . "valetudo_username" }}", "password": "{{ index . "valetudo_password" }}", "is_superuser": false}
          ]
        init-acl: |
          {allow, {user, "{{ index . "user_mqtt_username" }}"}, all, ["#"]}.
          {allow, {user, "{{ index . "dsmr_reader_username" }}"}, all, ["#"]}.
          {allow, {user, "{{ index . "esp_username" }}"}, all, ["#"]}.
          {allow, {user, "{{ index . "home_assistant_username" }}"}, all, ["#"]}.
          {allow, {user, "{{ index . "zigbee2mqtt_exporter_username" }}"}, all, ["#"]}.
          {allow, {user, "{{ index . "zigbee2mqtt_username" }}"}, all, ["#"]}.
          {allow, {user, "{{ index . "valetudo_username" }}"}, all, ["#"]}.
  dataFrom:
    - extract:
        key: EMQX
