---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v11
kind: Kustomization
resources:
  - ./aqua.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./crowdsec.yaml
  - ./descheduler.yaml
  - ./drone.yaml
  - ./dysnix.yaml
  - ./emxq.yaml
  - ./external-dns.yaml
  - ./gitea.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./kyverno.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./node-feature-discovery.yaml
  - ./piraeus.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./rook-ceph.yaml
  - ./stakater.yaml
  - ./traefik.yaml
  - ./vector.yaml
  - ./weave-gitops.yaml
