---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrepository_v12.json
apiVersion: source.toolkit.fluxcd.io/v12
kind: HelmRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 2h
  url: https://kyverno.github.io/kyverno/
