---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrepository_v12.json
apiVersion: source.toolkit.fluxcd.io/v12
kind: HelmRepository
metadata:
  name: node-feature-discovery
  namespace: flux-system
spec:
  interval: 2h
  url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
  timeout: 3m
