---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrepository_v12.json
apiVersion: source.toolkit.fluxcd.io/v12
kind: HelmRepository
metadata:
  name: rook-ceph
  namespace: flux-system
spec:
  interval: 2h
  url: https://charts.rook.io/release
  timeout: 3m
