---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrepository_v12.json
apiVersion: source.toolkit.fluxcd.io/v12
kind: HelmRepository
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 30m
  url: https://helm.gitops.weave.works
  timeout: 3m
