---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-lldap
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/security/lldap/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
