---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "econline-nl"
spec:
  secretName: "econline-nl-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "econline.nl"
  dnsNames:
    - "econline.nl"
    - "*.econline.nl"
