---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: agregarr
spec:
  components:
    - ../../../../components/kopiur/adopt-static
    - ../../../../components/kopiur/backup
    - ../../../../components/nfs-scaler
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/media/agregarr/app
  postBuild:
    substitute:
      APP: agregarr
      KOPIUR_VOLUMENAME: pvc-758db53b-6c78-4858-83c4-608bc7c430e3
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
