---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: miniflux
  namespace: selfhosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: kireque
        namespace: flux-system

  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/miniflux/miniflux
      tag: 2.0.45

    env:
      CREATE_ADMIN: "0"
      DATABASE_URL:
        valueFrom:
          secretKeyRef:
            name: database-miniflux-user
            key: POSTGRES_URL
      POLLING_SCHEDULER: "entry_frequency"
      POLLING_FREQUENCY: "15"
      RUN_MIGRATIONS: "1"
      OAUTH2_USER_CREATION: "1"
      OAUTH2_PROVIDER: oidc
      OAUTH2_REDIRECT_URL: "https://minifluxeconline.local/oauth2/oidc/callback"

    envFrom:
      - secretRef:
          name: miniflux-secret

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        ingressClassName: "external-nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-exteconline.local
        hosts:
          - host: &host "minifluxeconline.local"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 8080

    resources:
      requests:
        cpu: 12m
        memory: 64M
      limits:
        memory: 256M
