---
# TODO: add schema
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: context7-mcp
spec:
  groupRef:
    name: mcp-tools
  image: ghcr.io/stacklok/dockyard/npx/context7:3.2.5@sha256:8be4d07f6d4a47fc1ba2aa17b4a57376a51627f03acb23b84885f6494b9771de
  secrets:
    - name: context7-mcp-secret
      key: api_key
      targetEnvName: CONTEXT7_API_KEY
  transport: stdio
