---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dsmr-reader
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  dataFrom:
    - extract:
        key: DSMR-reader
      rewrite:
        - regexp:
            source: "(.*)"
            target: "dsmr_reader_$1"
  target:
    name: dsmr-reader-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DSMRREADER_ADMIN_USER: "{{ .dsmr_reader_username }}"
        DSMRREADER_ADMIN_PASSWORD: "{{ .dsmr_reader_password }}"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dsmr-reader-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: dsmr-reader-db-secret
    template:
      type: Opaque
      data:
        ATUIN_DB_URI: '{{ index . "uri" }}'
        DJANGO_DATABASE_HOST: '{{ index . "host" }}'
        DJANGO_DATABASE_PORT: '{{ index . "port" }}'
        DJANGO_DATABASE_USER: '{{ index . "user" }}'
        DJANGO_DATABASE_PASSWORD: '{{ index . "password" }}'
        DJANGO_DATABASE_NAME: '{{ index . "dbname" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-dsmr-reader
