---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dsmr-reader
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      dsmr-reader:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/xirixiz/dsmr-reader-docker
              tag: 5.11.0-2024.04.03
            env:
              DJANGO_TIME_ZONE: "Europe/Amsterdam"
              DSMRREADER_REMOTE_DATALOGGER_INPUT_METHOD: ipv4
              DSMRREADER_REMOTE_DATALOGGER_NETWORK_HOST: "10.1.4.45"
              DSMRREADER_REMOTE_DATALOGGER_NETWORK_PORT: "8088"
            envFrom:
              - secretRef:
                  name: dsmr-reader-secret
              - secretRef:
                  name: dsmr-reader-db-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 47m
                memory: 662M
              limits:
                memory: 662M

    service:
      app:
        controller: dsmr-reader
        ports:
          http:
            port: 80

    ingress:
      app:
        className: "internal-nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-int.econline.nl
        hosts:
          - host: dsmr-reader.econline.nl
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
