---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wyoming-whisper
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m

  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: rhasspy/wyoming-whisper
      tag: latest@sha256:785eb53debbb1d1c170f75aa5a3bdf0ea1a57b3a747641ea5f309a2e9dd3bfc4

    args:
      - --model
      - small
      - --language
      - en

    env:
      TZ: "America/Chicago"

    service:
      main:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.77.103
        ports:
          http:
            port: 10300
            protocol: TCP

    resources:
      requests:
        cpu: 500m
        memory: 250Mi
      limits:
        memory: 2500Mi

    volumeClaimTemplates:
      - name: data
        mountPath: /data
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: ceph-block
