---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app flux-mcp
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  targetNamespace: llm-system
  path: ./kubernetes/apps/llm-system/flux-mcp/app
  interval: 30m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: toolhive-operator-crds
  postBuild:
    substitute:
      APP: *app
