---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-bonob-main
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/cluster-0/apps/media/bonob/main"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false # no flux ks dependents
  dependsOn:
    - name: cluster-apps-navidrome-main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-bonob-kids
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/cluster-0/apps/media/bonob/kids"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false # no flux ks dependents
  dependsOn:
    - name: cluster-apps-navidrome-kids
