---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/onedr0p/jellyfin
      tag: 10.8.11@sha256:926e2a9f6677a0c7b12feba29f36c954154869318d6a52df72f72ff9c74cf494

    enableServiceLinks: false

    env:
      DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
      JELLYFIN_FFmpeg__probesize: 50000000
      JELLYFIN_FFmpeg__analyzeduration: 500000000

    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: "10.45.0.22"
        ports:
          http:
            port: 8096

    ingress:
      main:
        enabled: true
        ingressClassName: external-nginx
        hosts:
          - host: &host jellyfin.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    nodeSelector:
      intel.feature.node.kubernetes.io/gpu: "true"

    persistence:
      nfs-nas-media:
        enabled: true
        mountPath: /data/nas-media
        path: /volume3/Download
        server: synology.${SECRET_DOMAIN_LOCAL}
        type: nfs
      transcode:
        enabled: true
        type: emptyDir
      cache:
        enabled: true
        type: emptyDir

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 65539

    resources:
      requests:
        cpu: 100m
        gpu.intel.com/i915: 1
        memory: 9248M
      limits:
        gpu.intel.com/i915: 1
        memory: 9248M

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 30Gi
        storageClass: ceph-block