---
version: "3"

tasks:

  bootstrap:
    desc: Redeploy all of the Virtual Machines
    dir: '{{.PROJECT_DIR}}'
    cmds:
      - kubectl apply --server-side --kustomize ./kubernetes/bootstrap
      - sops --decrypt ./kubernetes/bootstrap/github-deploy-key.sops.yaml | kubectl apply -f -
      - cat ~/.config/sops/age/keys.txt | kubectl create secret generic sops-age --namespace=flux-system --from-file=age.agekey=/dev/stdin
      - kubectl apply -f ./kubernetes/flux/vars/cluster-settings.yaml
      - sops --decrypt ./kubernetes/flux/vars/cluster-secrets.sops.yaml | kubectl apply -f -
      - kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-community/helm-charts/main/charts/kube-prometheus-stack/crds/crd-prometheuses.yaml
      - kubectl apply --server-side --kustomize ./kubernetes/flux/config


