---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: selfhosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: kireque
        namespace: flux-system

  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: 1.16.5

    envFrom:
      - secretRef:
          name: paperless-secret
      - configMapRef:
          name: paperless-configmap

    service:
      main:
        ports:
          http:
            port: 8000

    ingress:
      main:
        enabled: true
        ingressClassName: "internal-nginx"
        annotations:
          nginx.ingress.kubernetes.io/auth-url: https://autheconline.local/oauth2/auth?allowed_groups=paperless
          nginx.ingress.kubernetes.io/auth-signin: https://autheconline.local/oauth2/start?rd=$scheme://$best_http_host$request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-email, x-auth-request-groups"
        hosts:
          - host: &host "paperlesseconline.local"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      nas-consume:
        enabled: true
        mountPath: /data/nas/consume
        type: nfs
        server: "nas.bjw-s.tech"
        path: /volume1/Docs/paperless/incoming
      nas-export:
        enabled: true
        mountPath: /data/nas/export
        type: nfs
        server: "nas.bjw-s.tech"
        path: /volume1/Docs/paperless/export

    resources:
      requests:
        cpu: 11m
        memory: 1812M
      limits:
        memory: 1812M

    volumeClaimTemplates:
      - name: data
        mountPath: /data/local
        accessMode: ReadWriteOnce
        size: 15Gi
        storageClass: ceph-block
