clusterName: ENC[AES256_GCM,data:SBqBHw==,iv:rIhlokOcRYq6poQWSG4FtpwArCM00mWOUu1kt6YdM7k=,tag:ppwJZpsLeXWxPSVZO/2/oA==,type:str]
clusterDNSSuffix: ENC[AES256_GCM,data:C6LEqzycIoB7DMRPGufX+g==,iv:Lm2d98XX6Cqeclo9eoLaE9IUyVhWQb7XmCfPu2pAvTY=,tag:Q/TUEpX3Nx7r2K5peWbQMA==,type:str]
clusterEndpointIP: ENC[AES256_GCM,data:WluN17zWQ+PhYQ==,iv:/D9kfhWwiQTwaQwPFIEyVeyS97536u6n2qkQt9mLR8Q=,tag:z+naTX6uF3ObffZrDf3aDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180mw9nde354qyrklgcylwdn42ql657j6vcpdud5gqpeyp7e9v4xsrdns9t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TEx0KzZMcXZaaHpDZWpI
            cjFvTUtRckpIU2dxSUlMQSt2TVdWQnBMcmgwCnUxdXZpNjdNMXcyV0xaVG1sS2R6
            TSt3OXRNalFPTDBEeTlTbHQrQjdHNncKLS0tIEFKZEMvY044MEVPSXczNWt4NTdD
            VDZFSXVOYW9LWTdwTUhGTUM1b0JDYk0K3sL0UHpbsKBqBc462RBnzq0KzU7dWOOk
            wTSU9AAr6IqErPHjTu2XHZlqOaaLw/ZyRaiyVhBfLSpThgAsEguPfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-03T14:47:01Z"
    mac: ENC[AES256_GCM,data:GAfYJ01BoGavuYSR7ffEEZuPTpb7PbRdwTVatGMf4WtueD2py2N7H08aVl0UtpbAPLGxr31Tig/YQF49U3IrWvQleUebiCnaFyaxkFGYLreT3hL7V+nD0SB0K7lzjQZS8iO+3fARulWscNu+lQGaPmORm4cm5Z22AkQZEAAx4e4=,iv:AkkNjtVMo7c/MBm6RDHj5i4mVvGm6NSqFIzHvCdSuYk=,tag:j0UOFvca1rBcH2+TPPXnoA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
