clusterName: ENC[AES256_GCM,data:SBqBHw==,iv:rIhlokOcRYq6poQWSG4FtpwArCM00mWOUu1kt6YdM7k=,tag:ppwJZpsLeXWxPSVZO/2/oA==,type:str]
clusterDNSSuffix: ENC[AES256_GCM,data:C6LEqzycIoB7DMRPGufX+g==,iv:Lm2d98XX6Cqeclo9eoLaE9IUyVhWQb7XmCfPu2pAvTY=,tag:Q/TUEpX3Nx7r2K5peWbQMA==,type:str]
clusterEndpointIP: ENC[AES256_GCM,data:Eikoz6Cofmo=,iv:yS0N2oHQUGfztL4EQaRFJbECp4YB+RCeYcDL2U/B1aI=,tag:jK6qhUGn6vJXvtbeGkUyDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180mw9nde354qyrklgcylwdn42ql657j6vcpdud5gqpeyp7e9v4xsrdns9t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TEx0KzZMcXZaaHpDZWpI
            cjFvTUtRckpIU2dxSUlMQSt2TVdWQnBMcmgwCnUxdXZpNjdNMXcyV0xaVG1sS2R6
            TSt3OXRNalFPTDBEeTlTbHQrQjdHNncKLS0tIEFKZEMvY044MEVPSXczNWt4NTdD
            VDZFSXVOYW9LWTdwTUhGTUM1b0JDYk0K3sL0UHpbsKBqBc462RBnzq0KzU7dWOOk
            wTSU9AAr6IqErPHjTu2XHZlqOaaLw/ZyRaiyVhBfLSpThgAsEguPfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-01T19:58:26Z"
    mac: ENC[AES256_GCM,data:HffbCPgL+odlL2Mg8YOXuw/POiXUgZq715PY3Ml0dhs42D1eTOUEUJ8ugyovpVr53hQUNxSIuIfDRJawJACkWFnZZCyDJFrYiD0cSbGjL9WF3ZtTdD+ZbuqXNsKL92Jk9f4td6qhT2N9/wjNR52MRFWhP77xdykph8gB3XiKJxQ=,iv:YoQRn1up9n691ORTS+jFHl6nZYNT8ktJSZ2el3wJf7c=,tag:E1arW34FPLjMso7+fsb4nQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
