apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:f1YIOxC2a3JoIQkHCAdb+UL/XWgNrwtRm1QeZhoe/tZXonn6bkgtig==,iv:s4K0D9JZhDMZSiDalIKjAnzb/SANVZGTFxBinSEPnUM=,tag:gmvCkuNNyplc6MzicXYeMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vq46r6697jer0udz6pjx9grgt5xlpg70wjvnw3l6pjmup4k57e4qnqn7vn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvb1hIUUFnV3JLR0Urakxq
            YURKRFRCMEZmS0xCMFp5eXZqTTd2TkhTUEJFCktJbHNNRElaekd4T01PTi9nUmtL
            U0txTGtNM3BYUUhIOEZ5T3NESUIzZFkKLS0tIEwzYXVKVk5udUNiWXBFV3lIZVFw
            VzlHb0ltWmw1TTE4VWVxZkY4NWdMWVUKMz6eYj2zVdIzq3uaHdl+ja0WjSS1yCDN
            4WspQth02TuSyuMChZ/PbJNfdTNtWUgazQE8FEmx1EdL2rM+gyJUQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-14T15:51:45Z"
    mac: ENC[AES256_GCM,data:B6YWtwOs86MF13HE6h9ISWzwgE72C9KX7I5S4bWuZ0Gc8pvJ5nlu2lNTp5iE9TxbIgqxyEgXGzDQ3wLUM0wuB5J85rZXOnNnLIFRnPlakVtfxnAP8qh/p4d+anxSg53Hk6K/ybNN4/sNUT2Y2Q6JeEOZxNbxefHh8FvSfs8ensw=,iv:afCYEMMInG9HRbIt4nzBEa+W0DVCkn+Z4DpVdXr+fWc=,tag:+1xrBrJsJAvLx9B4UgMD4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
