---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-mcp
spec:
  chartRef:
    kind: OCIRepository
    name: flux-mcp
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: flux-mcp
    transport: http
    readonly: false
    networkPolicy:
      create: false
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 1Gi
