---
# TODO: add schema
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: flux-mcp
spec:
  args:
    - serve
    - --transport=http
    - --port=9090
  groupRef:
    name: mcp-tools
  image: ghcr.io/controlplaneio-fluxcd/flux-operator-mcp:v0.53.0@sha256:ea3aa8c99c3731d261e1209fddc5bda7b66bafa6c816409c2ed07d58534c9d94
  mcpPort: 9090
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          readinessProbe:
            tcpSocket:
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: temp
              mountPath: /tmp
      serviceAccountName: flux-mcp
      volumes:
        - name: temp
          emptyDir: {}
  transport: streamable-http
