---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: kireque
        namespace: flux-system
  interval: 30m
  values:
    controller:
      type: statefulset

    image:
      repository: ghcr.io/kireque/calibre-web
      tag: 0.6.20@sha256:462de8582ffa12d5726ed781853e47b92b04ed0ec59b0772c12324dc25841977

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    enableServiceLinks: false

    env:
      CACHE_DIR: /cache

    service:
      main:
        ports:
          http:
            port: 8083

    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/auth-url: https://autheconline.local/oauth2/auth?allowed_groups=calibre-web
          nginx.ingress.kubernetes.io/auth-signin: https://autheconline.local/oauth2/start?rd=$scheme://$best_http_host$request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-email, x-auth-request-groups"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-parkeconline.local/css/base/calibreweb/nord.css"></head>';
            sub_filter_once on;
        ingressClassName: internal-nginx
        hosts:
          - host: &host calibre-webeconline.local
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      media:
        enabled: true
        mountPath: /data/nas-media
        path: /volume1/Media
        server: synology.econline.local
        type: nfs
      cache:
        enabled: true
        type: emptyDir
        mountPath: /cache

    resources:
      requests:
        cpu: 5m
        memory: 470M
      limits:
        memory: 470M

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block
