---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  chartRef:
    kind: OCIRepository
    name: jellyfin
  interval: 1h
  timeout: 15m
  values:
    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: jellyfin/jellyfin
              tag: 10.11.11@sha256:aefb67e6a7ff1debdd154a78a7bbb780fd0c873d8639210a7f6a2016ad2b35db
            env:
              TZ: Europe/Amsterdam
              JELLYFIN_CACHE_DIR: /cache
            probes:
              liveness:
                enabled: true
                spec:
                  failureThreshold: 5
                  periodSeconds: 30
                  timeoutSeconds: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /System/Info/Public
                    port: &port 8096
                  failureThreshold: 5
                  periodSeconds: 10
                  timeoutSeconds: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
              readOnlyRootFilesystem: true
            resources:
              claims:
                - name: gpu
              limits:
                memory: 8Gi
              requests:
                cpu: 100m
                memory: 512Mi
    defaultPodOptions:
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: jellyfin
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.econline.nl"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      cache:
        type: emptyDir
        globalMounts:
          - path: /cache
      config:
        existingClaim: "{{ .Release.Name }}"
      media:
        type: nfs
        server: gladius.home.econline.nl
        path: /mnt/tank/media
        globalMounts:
          - path: /media
            readOnly: true
      tmp:
        type: emptyDir
