---
# yaml-language-server: $schema=https://json.schemastore.org/kubernetes-persistentvolumeclaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-introskipper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: openebs-hostpath
