# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: security
stringData:
    1password-credentials.json:
        version: ENC[AES256_GCM,data:3w==,iv:K9i53gLFD9uz66SC+ep+zloDm759tWbm3tTOiGlxj8o=,tag:P7oauPNuZnRvUepQVwlxWA==,type:str]
        verifier:
            salt: ENC[AES256_GCM,data:n9/E6I4MCUNiLpQyBeuyJsmMJOyDFQ==,iv:lHpTr+PP6NZ1bSxqvAzEWkcoCm7r14AGyqiadbSzQkI=,tag:+ru0wWKvkThRMksnnFEVng==,type:str]
            localHash: ENC[AES256_GCM,data:KvixPfYMpb/Ubod1aJm/VlcGvahnWn7YmUhWG7Rfee6C8SUKdAxXmFQs2w==,iv:YJ4RcO00AZABASGYUR77+9vKD6PUrgRokXADQS0Jqio=,tag:PERfAoCGfVyPNCBkLU9V8Q==,type:str]
        healthVerifier: null
        encCredentials:
            kid: ENC[AES256_GCM,data:GZMs6t9l6uOxkKdIEF9+Ts0=,iv:6swbztopJGw+TgkbqGk8PKVPGex6KmZSItdsPPRZSk0=,tag:UsMNSk6SChN0Ua1u2Rmc4Q==,type:str]
            enc: ENC[AES256_GCM,data:fOdvYc4BiQ==,iv:1S3uQAEXTwYYcCsZq5psCSAPRxFQMlu/4MVogVhXUW0=,tag:tgtRQIUWg1oDTqsr5i508w==,type:str]
            cty: ENC[AES256_GCM,data:ut+GLR+98lTbo4g=,iv:lsog6DDT5THzfrq/LLknzjO2g8xcxUS2H6UR9+TSgaw=,tag:0nBile7bQ3NY7JLZGVaAaQ==,type:str]
            iv: ENC[AES256_GCM,data:RLEXNJNxZM1FV1NuXAkyHg==,iv:M4433/lR0pgSjY6uP7br/2bRoY+iFSddnQJlJeGqAr4=,tag:Tx4GLnco+RBrRWB6szpllQ==,type:str]
            data: ENC[AES256_GCM,data:bLxHSV8ubLNTDFKgkc5NquFkSifXJc9SYobwa8aMTekZDM56AzogjIkXlSLcuW3Bx2/6oHo/kdAK9fskPRdMzuzQj9pQX5ctW4iAdm+v9HDhTuTHWHXwTb1bb6KiAiZDx2S626YQ/2nKcQZQOTpuplQ6SueB2GaSOy+P6GUb/zMVCNbtlFmTZQo1LJ42XuDKpbHpPVdcgcG7isRVJ9dK/2peHimI/0PMi1BARNSGUInXQbzP6vT3W51GL/gdqwuEKduaqAYdJi6SLukREU9Et87DXOQRt0jurIimdU69LdqB0xDhFvbUkr4ttbgRCAfjAYWX+J0TVQPI8U7rz1/8g2/78SZaiQzEh5dPBHeSkMngwV4dWW8YSJ+JNipI4yprPmdM5JvcN1tbqWW1darWyc0FW3Qw0RIaLQ6a1t4pNRlPwDcB5KD+g5oSCE58keroMaogDgeraIROnC6M+czo0p/5Gr7qwHMeCucL/T81HehaLLptJw9RVJLgQ2cuzxlWHg4pJacQM9ZQrDunIGY+8aky6D/d4NLhpF66T9dLheXZw727XNBJfnpu/3CTsv2PmwgSyuOB7DoZ/ONCAEVucYTWkTCIEzHhi+xEjAaJrTqwDpKFLASLdxa1AQs+V0KOITsqaVxt82H4A3AuJ2LJqNiBtKSXBCC8LDdFRYVzHVCrmUZZA3YayKmWsWPQ/DvPLnQlTMs930hN0sKaxGj4PrvydxiCv1QQBsnU7VUAw5e/YXw0/D6X8LbbJdYFN8lqHIw3xrOgEv3zqL/WqBu5eD9Dq6emsglaKOuoCt4/fV00Tji5QatlijmuMWg6PBs8HPPbvolti4DPiGyowqjkrvuFbd7B+Icy3OpBtr0ZnQubmKi5,iv:s9BLSmV307yOY3t0kntlQD8876LEUCP1+ByMmiZVAZY=,tag:EbMqoWpRhsnxTl0kObg7Og==,type:str]
        uniqueKey:
            alg: ENC[AES256_GCM,data:Wiwa7oLMNw==,iv:MNmlNpNyhv5JtjjwOqw1SCy2ONncfu3/NvaF2RJDB14=,tag:yniauuF/Z83hjwtVKyvvEg==,type:str]
            kid: ENC[AES256_GCM,data:iDl5oEjVrn7Lm2cY/ym529uMHTZKTRUNsaE=,iv:lvA3wcN7q9b+piFoax5Dhjaj4WeR0LtrSLUEteV+pak=,tag:CNHEMKOOb+3Q6+RoLNn2Og==,type:str]
            k: ENC[AES256_GCM,data:HJ/WNXubFqLUo6vybfq4yOsoR51Ugk/E8Ugc+DE4zLw5n6idebmeYNQHXA==,iv:tmY01xG0LGI2lNua7CS7TW1eTupWaVGCWZhMU7vODXk=,tag:DWpls2Zsm87rBgYNbI8XBw==,type:str]
            key_ops:
                - ENC[AES256_GCM,data:aIzh7Q7GTQ==,iv:L0SSg8KN1PspCxTp45004TPSxwf/1N2JyeixCYuR2xk=,tag:2HdKYAIApN0WFSCwYG3FJA==,type:str]
                - ENC[AES256_GCM,data:F8uUtI0Zlw==,iv:quTxc0nDyC0jzf6fv4wWFDhHM6+Q0SxrqUtjPycIgUE=,tag:RHIdRgGugkWkai9DggGCRg==,type:str]
            ext: ENC[AES256_GCM,data:Dj84xA==,iv:Q5+eaJBjZEZE5rffL0xBuMGrqKV7YiG+rJAVbbYAPHs=,tag:3p8pBR5CfYTxh4CjGI/mHA==,type:bool]
            kty: ENC[AES256_GCM,data:gQbw,iv:vAkbL9qJI0eNQTJQi3l0xN+3SJuWN4IAF0ew6y+pP84=,tag:zYBv9Am/2dCYidWDLZR8hQ==,type:str]
        deviceUuid: ENC[AES256_GCM,data:H1EjwSVsXAMRNYiIyhUkvLj7petqfjrfQdE=,iv:CnJtuiWTGvMaCTjE7sBieXivY1hBtOzpVyocWnhLqSk=,tag:gnpTZIPV750QAN6RbHdCfA==,type:str]
    token: ENC[AES256_GCM,data:WWBAJKRuGeJZEgf9vZYdv10fXhYmMVoi3nFZrMD1dofJRn1p3yOVmyD/DO4MdHNignVZDqvTHILFMFL+Iw5P9lib2VvU57z+jIg0CMM+SlhglRzXktFBVYkTYnpff/gj1v4UQNHfLDvh3jT4tpRPLWV+RQ3eu2g4XHLvrt3sObyooKBJM0fwqoI+jSm/TvHdvA0tRgJhzQvdb8CgLRFxlIXJEGs7PPkbrOPhBId/VWcRsXMO5nAA8SB47TpJZF9K/EbxjOfhn5XcT5FuYzVqqv7Q5JMdk5QqFWk5jJn030dPvi7MZTvLNdmXD+1qwqiDLYXAojRVxZbLfJRh49ssW5LEZToofFwFXf4xRKhNUo9TlIaGkRdey3h4qDOZ+0Rbtp6QT6NU/Is8uh9MpaF72LvS5dPnd58fqLrJQnJwAr1Ua4lhJLl3fErnFr1QVvYiWhDePtW9ND4DylFu9sEpxAl6/1iQJ+KteOecHUNs9Hj50d/n6u6n8KOluASMw5TRx9uwUP7RQLz0zNaghVgdt/5lEbd9z3ejLcKa/uIvOHuCIEFLxhZcf//ihGr0qoZYAdkVNl7nf66ctLAV79lV+OijTKHW57sDsps+jAdOlLR9x3KDrHreJuocdk5HVapKfX+WVTMmdMcriQ7MeT67DqrpdigyMW1EdBNe+riv7VkjEJtGRG1MFgiPbNoJSzUzs1iWE9bXHrzA6QU94SY7iNkBUNVwfNrW/80WecEMn5RLbDI5S5p/zIZLFrBNOAGc+GE+AaKJCp50aOxMqDkFiZM1mzKMZd1GnCD3RGVAdFGmO2wjvtUR2UzlsGiDZnpSbQnXrcmQzPxMvo2yf0MITSqM,iv:uTpGEY1W9YCfTuHRlUIMv8UEBWbl0C9XIcCFbGEyPfQ=,tag:2YtEl9dt4YYJvPHenzKNHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180mw9nde354qyrklgcylwdn42ql657j6vcpdud5gqpeyp7e9v4xsrdns9t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNndhbUNUcFRrSXNmWllF
            WWwrNGNVdWc0ZS9oRVV1SXYwM3dOak43U3lvCnZ6eU1rQW1qcmhKYnExSmNtRk91
            M3hxWkdpUHN2NVkrT2hETTNhM21IUDgKLS0tIFBkbXdHdDU1WSsrbHVyNTJXU2JG
            cUM0N0xrOVdFcTBvNGRYTTZaRTBCUTAKSCDfX8G6uAdB/k7wPImO51XNJk8XgvG0
            mMAbkiKxI10XZNVlZkmyD6SfDJf7Ag4EzkGATgI431kVku4AXCl63A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-08T07:49:51Z"
    mac: ENC[AES256_GCM,data:PL/fg6zRqteulE/RWGh+xLpcU9cHOK7SfV0rNamUw+0h9Dym2Yn5kLY+0wbXq/0ao1eZrYuJ9keOXl7SAJF8lYhxpTOEeWdF+p6D9boENOatk1cgj69AtYDPHMMQayz/iXmsz/6bAbE4e2nuUdYabFVFhRj4xjFgK4OLTaGA2u0=,iv:R9RYoIzdpiHhzj74Ycj2vbdJbH3uUt160ZBq70+3uVc=,tag:eGrhNrX6nLEa2jjp+Oo97w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
