apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: security
stringData:
    token: ENC[AES256_GCM,data:1l3lWfjrnMQKT52/idQ9QmVwI7k3Rl0FLCqe9/kWL1pfQpw9ughP/yDAfAXWYGy2OaeKDuv5ZkF9rLdLpQmdIZuDNoJlIQdjbwuffzNbgf4c5cnyfPpwF0tHHKZSDNzboj0y2FhpZKjev8Ns1LRRJv4xtzPyE/yL3xpcFXfzVFHlye1V4tRtLEwV6iSChl9jTHK2xmo5J2f2E3y7uhodeaj4C5tOadv3+Lwt68WUtU3hLd1f57XOVABdeubV+MIsaZMoWuEby/oYzkUtz080AOQQ6u92QF77OTpG3/aQDpNzrlvyT6Fucb/l0cA5Y8eAfwpo0ztN01h/rTD2hyYDJYIsHqUJ+ADU5EiEJ6yisYNzIEIRslnfLkMeV6BRkEC4R405uArL7nU4QhudcAjAm/kjaW8dSjzE7sw8dnvrPkd6g7SIXlHbGLl1qijQoPmwDtbcrZjfBn21TwimIVIHtTRvMPF8BOvWVo9S0IkZoD3fpplChrdO6U2HizCtQJDu1kioGUAYhZmLmGGxnp6njqiq56CD+lCV02iKRsyNMRb8lLjXtbfOzDCvWsZW7xATBe3uKItiaV/RVRZjA+gThmyp+uXbW23P95nJqXIeWf/cmVGui45E87HCY8dNGImMLbqd56o7yaNKrlmEIkok1k+Y8mViIVRupz8LuIuwy0pAriBpBN5CBPlGJDv9a7sg4PK0R+qbpBouw7y0Sh6ZAc6usCcT5vXzAXr41ZrkmyIAd4C8/nNaC0o2UxNNfKU7UIeNK/xmmjN5fL9KtC8clvoIOYILs6YRnMkGKlrFi72QwwaDcj4UAMGjrQgxk3+vsklGkW/zWafI2NZQmd/zdMj230T2x1PEoiZSrG5PMVmlH/99Cij9yATXkO3rJKWr89qqOhkG4GRTdDXNZ8J27iZr+Z+fCpY4nsY=,iv:AmtlKdk/7u40BQy4/fs+OOtDrCigtWCbyOP8ZixzyMI=,tag:G//2OUJi9i+y1skazCPdIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uk0y2ahfavgsgqvrtg5a22w5gytpdmjuatxtcw6kntmxhlcgreesuwzw5s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTjJIT0tybVViZWhscEdZ
            Y3k3Z0FTUWJWek9iSERWQ1RveHBGNU5abkNrCkI5ajRXWFl5SW1RTlVwUzlMRDdG
            S0RIb21MTmNKUHhYQ2tSUXI0OFFIUUUKLS0tIHlNeSswNHUzSURYWjJoMGRSdUhY
            Y1h2cWdiQ1JHanRCck5MN3FJY2doWVkK4KQvXqdm20tNFOvnmgjLQnL5kVXAzH0Y
            G8/pLN99UqKcTVhzXE8TtmE1jvP1P6N1stE+arXeeImgTVyW810w8Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hawjtl6fm5czl8cun0ve7jvsmpqpn3qlxl2lnx7ndt7682tmva2qz3drfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNG0vZUJiTzc3bU5ib09Q
            SUMvZ0ZTUERaT1ZjMDJzRmdWVytxK0ZMN0JZCmdEM2xtN2k3cVFwT01XNUhiWlFj
            aFdqRm1nYlFiVTc0SjE0bFd1V1NJc3cKLS0tIFR6SVVCMG5pV1NLYVBmUDN0N3RT
            aGhXRzBtbGRoLzhldUt0QjRxRWNNdEUKF4qOBTWgDlwQnI1ka5w1NdmMkYRMxsre
            U2Sd0tt797URBUeLAVyU5UTcRC2mHUxkeSBhHhW+5upns2J2eKVX0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T09:45:15Z"
    mac: ENC[AES256_GCM,data:14veRcryAQl8XNppP5jIl1W3YvTZgnrlNyD6rX56u+/vOsR9sEU6MzpglPx8v4j/xurf4k8coeVbVgyYxCDyOf9CZBEJvaFfiDlDi2cOh3VCR3m1dnEd4gzN0jdBm4/cC+fhbFHkbuks+WpIQBPOJ2ap5U98UrHol3LqnfQw7M4=,iv:f4GYJAV8PlwEyGc+h+n1UfpyihxhbgR4/Y38PyTIXHM=,tag:9knkPLUQ3+v2k5sKH0CuiA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
