apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:aDJN7LGDe206SJ6rqTKUbv5v9tsY91HYxOAVJr3NgFDnHc8RPkO0og==,iv:TW1Dlts2e/JNj9rKJJSuV9XZE3uCkhsfMYNMoW5xyVA=,tag:SM/Jt7qWX9Gm35UckUuBSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180mw9nde354qyrklgcylwdn42ql657j6vcpdud5gqpeyp7e9v4xsrdns9t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWW9VZHY5OU1FcHNDSjRt
            NmxGMGtQU3hreHI5Wm1BM0JYVlVvMnBMSUY0CkZBWDJ6bTMyV2YxWnZ1d25TNzdo
            REZhUysvOHFkajU5VVNxWGhWcWlZQUUKLS0tIGtPeEhzaFZSTUdianE5N2d0OUt2
            NzdDN3RZeHVuYXFaR1VtWFJ4a3RsNWcKp2sJ9JKSDC0IKpheWrJOPdVnc8QeRp4o
            vFLpX8i1xgrjjycDtP+v1kpiILzJ+sbvdhXAY+PYd9B0rgsdaH3uyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-24T19:45:36Z"
    mac: ENC[AES256_GCM,data:UFL6pQ+aXrNK7RklbNMlBqxKL52Xv+q+82x+W0S8yADDwHBQ2i1Obo1dWrm0Ntlq63VXdX/k3z/ZDGZKQEHNqgWWMgmW8Ph6OqmnIQo7UUrkQVGey/V7egfifCkCqS6d0zq02JLdUL1KG3Z9hgPraytuWhOLVcHLFPj1aWh8dOI=,iv:9e/gFlbmvlgH66QkvtNnm10IlV5PpDx8p0Kb0tQgxJ0=,tag:v/X6LcyJIkfjKfAeZA3afQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
