---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lldap
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      replicas: 1
      strategy: Recreate
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/lldap/lldap
      # TODO: Switch to release tag on next release
      tag: latest-alpine@sha256:c75544bf15baefc8cac356abb9ec360a7f251d16d9b71388655f213214269dad

    env:
      LLDAP_HTTP_PORT: &port 80
      LLDAP_HTTP_URL: https://lldap.${SECRET_DOMAIN}
      LLDAP_LDAP_PORT: &ldapPort 389

    envFrom:
      - secretRef:
          name: lldap-secret

    service:
      main:
        ports:
          http:
            port: *port
          ldap:
            enabled: true
            port: *ldapPort

    ingress:
      main:
        enabled: true
        ingressClassName: internal-nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-ext.${SECRET_DOMAIN}
        hosts:
          - host: &host "lldap.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        type: pvc
        existingClaim: data-lldap

    resources:
      requests:
        cpu: 5m
        memory: 128Mi
      limits:
        memory: 512Mi
