---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-nfs
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Mi
  nfs:
    path: "/volume3/Backup/CPGO"
    server: nas.home.econline.nl
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-nfs
