---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/gitrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api-crd
spec:
  interval: 30m
  url: https://github.com/kubernetes-sigs/gateway-api
  ref:
    # renovate: depName=kubernetes-sigs/gateway-api datasource=github-releases
    tag: v1.2.1
  ignore: |
    # exclude
    /*
    config/crd/standard/gateway.networking.k8s.io_gateways.yaml
    config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
    config/crd/experimental/*
    config/crd/stable/*
    # include
    !config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
    !config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
    !config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
    !config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
    !config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
    !config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api
spec:
  prune: true
  sourceRef:
    kind: GitRepository
    name: gateway-api-crd
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 5m
