apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-down-fri-sun
spec:
  schedule: "0 1 * * 5,6,0" # At 01:00 Friday, Saturday, Sunday
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1 # Automatically delete completed jobs
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: scale-job-account
          restartPolicy: Never
          containers:
            - name: kubectl-container
              image: bitnami/kubectl
              command:
                - "/scripts/scale-deployments.sh 0"
              volumeMounts:
                - name: script-volume
                  mountPath: /scripts
                  subPath: scale-deployments.sh
                  readOnly: true
          volumes:
            - name: script-volume
              configMap:
                name: scale-deployments
                defaultMode: 0755
