apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-up
spec:
  schedule: "5 19 * * *" # At 19:05 every day
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1 # Automatically delete completed jobs
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: scale-job-account
          restartPolicy: Never
          containers:
            - name: kubectl-container
              image: bitnami/kubectl
              command:
                - "/bin/bash"
                - "-c"
                - "/scripts/scale-deployments.sh 1"
              volumeMounts:
                - name: script-volume
                  mountPath: /scripts/scale-deployments.sh
                  subPath: scale-deployments.sh
                  readOnly: true
          volumes:
            - name: script-volume
              projected:
                defaultMode: 0775
                sources:
                  - configMap:
                      name: scale-deployments
                      items:
                        - key: scale-deployments.sh
                          path: scale-deployments.sh
