---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yaml
  - cronjob-scale-up.yaml
  - cronjob-scale-down-fri-sun.yaml
  - cronjob-scale-down-mon-thu.yaml
configMapGenerator:
  - name: scale-deployments
    files:
      - scale-deployments.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled