---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-proxy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mcp-proxy-secret
    template:
      data:
        MCP_SECRET_PATH: "{{ .MCP_SECRET_PATH }}"
        AUTH_TOKEN: "{{ .AUTH_TOKEN }}"
  dataFrom:
    - extract:
        key: ha-mcp
    - extract:
        key: mcp-proxy
