---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads

components:
  - ../../components/alerts
  - ../../components/kopiur/secret
  - ../../components/namespace

patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: _
        annotations:
          volsync.backube/privileged-movers: "true"
        labels:
          resource.kubernetes.io/admin-access: "true"
    target:
      kind: Namespace

resources:
  - ./bazarr/ks.yaml
  - ./chaski/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
