---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/onedr0p/sabnzbd
      tag: 4.1.0@sha256:5db09d90352b5ee77cde948c55d20fedca69e63f0cc86d607c01ac82c5a1bf48

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    env:
      SABNZBD__PORT: &port 8080
      SABNZBD__HOST_WHITELIST_ENTRIES: >-
        sabnzbd,
        sabnzbd.downloads,
        sabnzbd.downloads.svc,
        sabnzbd.downloads.svc.cluster,
        sabnzbd.downloads.svc.cluster.local,
        sabnzbd.${SECRET_DOMAIN}
      SABNZBD__API_KEY:
        valueFrom:
          secretKeyRef:
            name: sabnzbd-secret
            key: api_key
      SABNZBD__NZB_KEY:
        valueFrom:
          secretKeyRef:
            name: sabnzbd-secret
            key: nzb_key

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: internal-nginx
        hosts:
          - host: &host "sabnzbd.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      media:
        enabled: true
        existingClaim: nas-media
        mountPath: /data/nas-media

    resources:
      requests:
        cpu: 5m
        memory: "1024M"
      limits:
        memory: "4096M"

    volumeClaimTemplates:
      - name: config
        mountPath: /config

        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block
