---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux
spec:
  chart:
    spec:
      chart: flux2
      version: 2.14.1
      sourceRef:
        kind: HelmRepository
        name: fluxcd-community
        namespace: flux-system
  interval: 30m
  valuesFrom:
    - kind: ConfigMap
      name: flux-helm-values
