---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 30m
  releaseName: rook-ceph
  chart:
    spec:
      chart: rook-ceph
      version: v1.13.3
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  values:
    crds:
      enabled: true

    csi:
      csiAddons:
        enabled: true

      kubeletDirPath: /var/lib/kubelet
      enableCSIHostNetwork: true
      pluginTolerations:
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"

      csiRBDProvisionerResource: |
        - name : csi-provisioner
          resource:
            requests:
              memory: 128Mi
              cpu: 25m
        - name : csi-resizer
          resource:
            requests:
              memory: 128Mi
              cpu: 25m
        - name : csi-attacher
          resource:
            requests:
              memory: 128Mi
              cpu: 25m
        - name : csi-snapshotter
          resource:
            requests:
              memory: 128Mi
              cpu: 25m
        - name : csi-rbdplugin
          resource:
            requests:
              memory: 512Mi
              cpu: 50m
        - name : csi-omap-generator
          resource:
            requests:
              memory: 512Mi
              cpu: 50m
        - name : liveness-prometheus
          resource:
            requests:
              memory: 128Mi
              cpu: 25m

    monitoring:
      enabled: true

    pspEnable: false

    resources:
      requests:
        cpu: 109m
        memory: 204M
