---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app minio
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      minio:
        labels:
          nfsMount: "true"
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: quay.io/minio/minio
              tag: RELEASE.2024-04-18T19-09-19Z
            env:
              MINIO_API_CORS_ALLOW_ORIGIN: https://minio.econline.nl,https://s3.econline.nl
              MINIO_BROWSER_REDIRECT_URL: https://minio.econline.nl
              MINIO_PROMETHEUS_JOB_ID: minio
              MINIO_PROMETHEUS_URL: http://thanos-query-frontend.monitoring.svc.cluster.local:10902
              MINIO_PROMETHEUS_AUTH_TYPE: public
              MINIO_SERVER_URL: https://s3.econline.nl
              MINIO_UPDATE: "off"
            envFrom:
              - secretRef:
                  name: *app
            args:
              - server
              - /data
              - --console-address
              - :9001
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /minio/health/live
                    port: 9000
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 6
              readiness: *probes
            securityContext:
              privileged: true
              runAsUser: 99
            resources:
              requests:
                memory: 100Mi
                cpu: 100m
              limits:
                memory: 3Gi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 9001
          s3:
            port: 9000
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: s3
            scheme: http
            path: /minio/v2/metrics/cluster
            interval: 1m
            scrapeTimeout: 10s
    ingress:
      app:
        className: "internal-nginx"
        hosts:
          - host: &hostName minio.econline.nl
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *hostName
      api:
        enabled: true
        className: internal-nginx
        hosts:
          - host: &s3Host s3.econline.nl
            paths:
              - path: /
                service:
                  identifier: app
                  port: s3
        tls:
          - hosts: [*s3Host]
    persistence:
      data:
        enabled: true
        type: nfs
        server: nas.home.econline.nl
        path: /volume3/docker/minio_k8s
        globalMounts:
          - path: /data