---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-blackbox-exporter
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/cluster-0/apps/monitoring/blackbox-exporter/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false # no flux ks dependents
  dependsOn:
    - name: cluster-apps-kube-prometheus-stack
