apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:ozgLD2Jp/Njc8F8QnNYD+BxGjtwE7FLzJiT3RJrTqtDs6tWfDg==,iv:0ZymJLVKfmJNfFrIRGOAe6+7q6WMKh035F0PLQhAiHs=,tag:ZwlFjL2vsDZgZnRut9YrVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mtzvncgylzrqrf3m6e4wpxt8sk6zq59mdraehr7lhxksyltmwdksl0ltrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRGYyQWZYcVBvaEhRZDVY
            QUt5QlhSSzMvNHkwb1JQbEVWL3pEczF5OHlnCk11VWRLdWs2YUYzbjN5VVcrTExC
            VDV6NG9sOUhUOHM2cmxZMy9WaVhLbUUKLS0tIFhRTU5CWG5TVVF6dkN2dzgva3JE
            ckFYcld6a2gvSEhVRGdRa1phZHlCMHMKE4LdCRI3rMw6+YZ5ojGcYrkZxfUPi+Dw
            UrK/KKR++qmUHnj1OKrVtTsIsTpx8L4FYSuzNkeFjAFne0mMkTSDRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-17T19:12:22Z"
    mac: ENC[AES256_GCM,data:ZH2ff61+Vhv2KOEjL4jnTkwKi+cVYEYkWQCM2km8SFUcYAntMqWOfAmhgzmQK/QwxK19SSul0hXkthJtphkM62lPHyUBohQ+xfvKgGrCVQ1RwHSsZKIHDo0REXJ61yrihW9r2lSS6iT7vKLRWEDleowNleQN9kXq6XmclvkrA1c=,iv:DuDccZJgCLUuPyrkWfGP78GJfFDyRcHWSwfdisFAgMo=,tag:rfh9+fU8sPo99nRZobUQRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
