---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prowlarr
spec:
  components:
    - ../../../../components/kopiur/adopt-static
    - ../../../../components/kopiur/backup
    - ../../../../components/nfs-scaler
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/downloads/prowlarr/app
  postBuild:
    substitute:
      APP: prowlarr
      KOPIUR_VOLUMENAME: pvc-fc386b5e-4b3f-4544-a15a-54c8bfa72c33
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: downloads
  wait: false
