---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: series-cleanup
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: kireque
        namespace: flux-system

  values:
    controller:
      type: cronjob
      cronjob:
        schedule: "10 */6 * * *"
        ttlSecondsAfterFinished: 86400

    podSecurityContext:
      runAsUser: 1031
      runAsGroup: 100
      fsGroup: 2000
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    restartPolicy: OnFailure

    image:
      repository: ghcr.io/kireque/series-cleanup
      tag: 3.1.0@sha256:4ebc472ba50df978a5f947708d48577bbd7e2ee01c16088b97df460acafc776a

    envFrom:
      - secretRef:
          name: series-cleanup-secret

    service:
      main:
        enabled: false

    persistence:
      config:
        enabled: true
        existingClaim: series-cleanup-data
      settings:
        enabled: true
        type: configMap
        name: series-cleanup-configmap
        subPath: settings.json
        mountPath: /config/settings.json
        defaultMode: 0775
        readOnly: true
      nfs-nas-media:
        enabled: true
        mountPath: /storage/media
        path: /volume1/Media
        server: synology.econline.local
        type: nfs
