---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname scrypted
  namespace: flux-system
spec:
  targetNamespace: home-automation
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  timeout: 5m
  path: "./kubernetes/main/apps/home-automation/scrypted/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false
  dependsOn:
    - name: multus-networks
    - name: rook-ceph-cluster
    - name: volsync
    - name: external-secrets-stores
  postBuild:
    substitute:
      APP: *appname
      VOLSYNC_CLAIM: scrypted-config
      VOLSYNC_CAPACITY: 5Gi
