---
- hosts:
    - storage
  gather_facts: false
  become: false
  any_errors_fatal: true

  environment:
    OP_CONNECT_HOST: "{{ lookup('env', 'OP_CONNECT_HOST') }}"
    OP_CONNECT_TOKEN: "{{ lookup('env', 'OP_CONNECT_TOKEN') }}"

  pre_tasks:
    - name: Gathering facts
      ansible.builtin.gather_facts:
      become: true
      tags:
        - always

  roles:
    - nas.apps
