---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2023.11.0@sha256:6785d286ffcb400e62d1a58499817a63ce2cf5b0d82d2352beb3c235512f710f

    podAnnotations:
      k8s.v1.cni.cncf.io/networks: |
        [{
          "name":"multus-iot",
          "namespace": "networking",
          "ips": ["192.168.10.200/24"]
        }]

    # env:
    #   SECRET_RECORDER_DB_URL:
    #     valueFrom:
    #       secretKeyRef:
    #         name: home-assistant-pguser-home-assistant
    #         key: uri

    envFrom:
      - secretRef:
          name: home-assistant-secret

    service:
      main:
        ports:
          http:
            port: 8123

    ingress:
      main:
        enabled: true
        ingressClassName: external-nginx
        annotations:
          # external-dns.alpha.kubernetes.io/target: ingress-ext.${SECRET_DOMAIN}
        hosts:
          - host: &host "domo.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      deploy-key:
        enabled: true
        type: secret
        name: home-assistant-secret
        defaultMode: 256
        subPath:
          - path: GH_DEPLOY_KEY
            mountPath: /root/.ssh/id_rsa

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    resources:
      requests:
        cpu: 47m
        memory: 1254M
      limits:
        memory: 1254M

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block
