---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: kireque
        namespace: flux-system

  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2023.7.2@sha256:27d23836fb155e9e731d2d35f3a62e4c8d8d49e97e910a661ca1de816416ca96

    podAnnotations:
      k8s.v1.cni.cncf.io/networks: |
        [{
          "name":"multus-iot",
          "namespace": "network",
          "ips": ["10.1.3.151/24"]
        }]

    env:
      SECRET_RECORDER_DB_URL:
        valueFrom:
          secretKeyRef:
            name: database-home-assistant-user
            key: POSTGRES_URL

    envFrom:
      - secretRef:
          name: home-assistant-secret

    service:
      main:
        ports:
          http:
            port: 8123

    ingress:
      main:
        enabled: true
        ingressClassName: "external-nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-exteconline.local
        hosts:
          - host: &host "domoeconline.local"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      deploy-key:
        enabled: true
        type: secret
        name: home-assistant-secret
        defaultMode: 256
        subPath:
          - path: GH_DEPLOY_KEY
            mountPath: /root/.ssh/id_rsa

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    resources:
      requests:
        cpu: 47m
        memory: 1254M
      limits:
        memory: 1254M

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block
