---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: piped
spec:
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      backend:
        strategy: RollingUpdate
        annotations:
          secret.reloader.stakater.com/reload: piped-secret

        containers:
          app:
            image:
              repository: 1337kavin/piped
              tag: latest@sha256:e9938cdda0745c4986d4add0f255777d3989849b851f290d94a4ab2b21c25384
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 500Mi
              limits:
                memory: 2000Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              seccompProfile:
                type: RuntimeDefault

      frontend:
        strategy: RollingUpdate

        containers:
          app:
            image:
              repository: ghcr.io/bjw-s-labs/piped-frontend
              tag: 2024.10.13@sha256:07ab90aa25302bcc6673d7a52b5d4b129490a8fb543d5648b87ed1d366ce547e
            env:
              BACKEND_HOSTNAME: piped-api.econline.nl
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true

      ytproxy:
        strategy: RollingUpdate

        containers:
          app:
            image:
              repository: 1337kavin/piped-proxy
              tag: latest@sha256:38e511b8d8ee52c41e1ba2d0d757a30089458d283d1eda9eb757d866f5ff8917
            command:
              - /app/piped-proxy
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 500Mi
              limits:
                memory: 2000Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              seccompProfile:
                type: RuntimeDefault

      update-subscriptions:
        type: cronjob

        cronjob:
          schedule: "@daily"
          concurrencyPolicy: Forbid
          successfulJobsHistory: 0
          failedJobsHistory: 1

        containers:
          app:
            image:
              repository: ghcr.io/bjw-s-labs/piped-scripts
              tag: 0.0.1@sha256:55dcbc2d65eb47d7a7f2c49c4fba1bc05ab3a715ae5b3f63a9653d804c704e69
            env:
              SCRIPT_NAME: update_subscriptions.sh
              PIPED_BACKEND: http://piped-backend.media.svc.cluster.local:8080
            envFrom:
              - secretRef:
                  name: piped-db-secret
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              seccompProfile:
                type: RuntimeDefault

    service:
      backend:
        controller: backend
        ports:
          http:
            port: 8080
      frontend:
        controller: frontend
        ports:
          http:
            port: 8080
      ytproxy:
        controller: ytproxy
        ports:
          http:
            port: 8080

    ingress:
      backend:
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-ext.econline.nl
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "https://piped.econline.nl, https://piped-api.econline.nl, https://piped-proxy.econline.nl"
        className: "external-nginx"
        hosts:
          - host: piped-api.econline.nl
            paths:
              - path: /
                service:
                  identifier: backend
                  port: http
      frontend:
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-int.econline.nl
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "https://piped.econline.nl, https://piped-api.econline.nl, https://piped-proxy.econline.nl"
        className: "internal-nginx"
        hosts:
          - host: piped.econline.nl
            paths:
              - path: /
                service:
                  identifier: frontend
                  port: http
      ytproxy:
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-int.econline.nl
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "https://piped.econline.nl, https://piped-api.econline.nl, https://piped-proxy.econline.nl"
        className: "internal-nginx"
        hosts:
          - host: piped-proxy.econline.nl
            paths:
              - path: /
                service:
                  identifier: ytproxy
                  port: http

    persistence:
      config:
        type: secret
        name: piped-secret
        advancedMounts:
          backend:
            app:
              - path: /app/config.properties
                subPath: config.properties
                readOnly: true
