---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation

components:
  - ../../components/alerts
  - ../../components/kopiur/secret
  - ../../components/namespace

patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: _
        annotations:
          volsync.backube/privileged-movers: "true"
        labels:
          resource.kubernetes.io/admin-access: "true"
    target:
      kind: Namespace

resources:
  - ./esphome/ks.yaml
  - ./home-assistant/ks.yaml
  # - ./home-assistant-gladius/ks.yaml
  - ./frigate/ks.yaml
  - ./mosquitto/ks.yaml
  - ./zigbee2mqtt/ks.yaml
