---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bonob-main
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: kireque
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/simojenki/bonob
      tag: v0.6.8

    env:
      BNB_PORT: 4534
      BNB_SONOS_AUTO_REGISTER: true
      BNB_SONOS_DEVICE_DISCOVERY: true
      BNB_SONOS_SEED_HOST: 10.1.3.61
      BNB_SONOS_SERVICE_ID: 246
      BNB_SONOS_SERVICE_NAME: Library - Main
      BNB_SUBSONIC_URL: https://navidrome-maineconline.local
      BNB_URL: https://bonob-maineconline.local

    service:
      main:
        ports:
          http:
            port: 4534

    ingress:
      main:
        enabled: true
        ingressClassName: internal-nginx
        hosts:
          - host: &host bonob-maineconline.local
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    resources:
      requests:
        cpu: 5m
        memory: 128M
      limits:
        memory: 128M
