---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-iot",
                "namespace": "network",
                "ips": ["10.1.4.151/24"]
              }]
          securityContext:
            runAsUser: 65534
            runAsGroup: 65533
            fsGroup: 65533
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/home-assistant
              tag: 2025.1.0@sha256:a3e6b1301107c5ca4dd3e1e7fa25edd0618acc9f812c75674cce7481fb05c759
            envFrom:
              - secretRef:
                  name: home-assistant-secret
            resources:
              requests:
                cpu: 47m
                memory: 2Gi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.96.2@sha256:6b8c0e944caec80057e71d2c2f352cee38fe00ae4b7515fc4458eb300844f699
            args:
              [
                "--auth",
                "none",
                "--disable-telemetry",
                "--disable-update-check",
                "--user-data-dir",
                "/config/.code-server",
                "--extensions-dir",
                "/config/.code-server",
                "--port",
                "12321",
                "/config",
              ]
            env:
              HASS_SERVER: http://localhost:8123
              HASS_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: home-assistant-secret
                    key: VSCODE_TOKEN
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi

    service:
      app:
        controller: home-assistant
        ports:
          http:
            port: 8123
          code-server:
            port: 12321

    ingress:
      app:
        enabled: true
        className: "internal-nginx"
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$1
        hosts:
          - host: hass.econline.nl
            paths:
              - path: /(.*)
                service:
                  identifier: app
                  port: http
              - path: /code/(.*)
                service:
                  identifier: app
                  port: code-server

    persistence:
      config:
        existingClaim: home-assistant-config
        advancedMounts:
          home-assistant:
            app:
              - path: /config
            code-server:
              - path: /config
      tmpfs:
        type: emptyDir
        advancedMounts:
          home-assistant:
            app:
              - path: /tmp
                subPath: hass-tmp
            code-server:
              - path: /tmp
                subPath: code-server-tmp
              - path: /nonexistent
                subPath: nonexistent
