---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-iot",
                "namespace": "network",
                "ips": ["10.1.4.151/24"]
              }]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2024.7.2
            envFrom:
              - secretRef:
                  name: home-assistant-secret
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 47m
                memory: 2Gi
              limits:
                memory: 2Gi

          # Configure the code-server sidecar
          code:
            dependsOn: app
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.91.1
            args:
              - --auth
              - "none"
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"
              - --port
              - "8081"
              - "/config"

    service:
      app:
        controller: home-assistant
        ports:
          http:
            port: 8123
      # Configure a service for the code-server sidecar
      code:
        type: ClusterIP
        controller: home-assistant
        ports:
          http:
            port: 8081

    ingress:
      app:
        enabled: true
        className: "external-nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-ext.econline.nl
        hosts:
          - host: hass.econline.nl
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

      # Configure an Ingress for the code-server sidecar
      code:
        className: "internal-nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-int.econline.nl
        hosts:
          - host: &host-code hass-code.econline.nl
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: code
                  port: http

    persistence:
      config:
        existingClaim: home-assistant-config
        # advancedMounts:
        #   home-assistant:
        #     app:
        #       - path: /config
        globalMounts:
          - path: /config

      deploy-key:
        type: secret
        name: home-assistant-secret
        defaultMode: 256
        globalMounts:
          - path: /root/.ssh/id_rsa
            subPath: GH_DEPLOY_KEY
