---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-iot",
                "namespace": "network",
                "ips": ["10.1.4.151/24"]
              }]
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/home-assistant
              tag: 2024.11.1@sha256:a3dd7577c28771702b21f817ad86600056467c2c7f45d261a1e7241910ddc2e2
            envFrom:
              - secretRef:
                  name: home-assistant-secret
            resources:
              requests:
                cpu: 47m
                memory: 2Gi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.95.2@sha256:51b9ff106f67bfe56aa88c7e63e7413276d0b509fb85290c3d361a38e97bfa8c
            args: [
              "--auth", "none",
              "--disable-telemetry", "--disable-update-check",
              "--user-data-dir", "/config/.code-server",
              "--extensions-dir", "/config/.code-server",
              "--port", "12321",
              "/config"
            ]
            env:
              HASS_SERVER: http://localhost:8123
              HASS_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: home-assistant-secret
                    key: VSCODE_TOKEN
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi

    service:
      app:
        controller: home-assistant
        ports:
          http:
            port: 8123
          code-server:
            port: 12321

    ingress:
      app:
        enabled: true
        className: "internal-nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-int.econline.nl
          nginx.ingress.kubernetes.io/rewrite-target: /$1
        hosts:
          - host: hass.econline.nl
            paths:
              - path: /(.*)
                service:
                  identifier: app
                  port: http
              - path: /code/(.*)
                service:
                  identifier: app
                  port: code-server

    persistence:
      config:
        existingClaim: home-assistant-config
        advancedMounts:
          home-assistant:
            app:
              - path: /config
            code-server:
              - path: /config
      tmp:
        type: emptyDir
      deploy-key:
        type: secret
        name: home-assistant-secret
        defaultMode: 256
        advancedMounts:
          home-assistant:
            code-server:
              - path: /home/coder/.ssh/id_rsa
                subPath: GH_DEPLOY_KEY
