---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sabnzbd
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: sabnzbd-secret
    creationPolicy: Owner
    template:
      data:
        SABNZBD__API_KEY: "{{ .SABNZBD_API_KEY }}"
        SABNZBD__NZB_KEY: "{{ .SABNZBD__NZB_KEY }}"
  data:
    - secretKey: SABNZBD_API_KEY
      remoteRef:
        key: sabnzbd
        property: api_key
    - secretKey: SABNZBD__NZB_KEY
      remoteRef:
        key: sabnzbd
        property: nzb_key
