---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: navidrome-kids
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: kireque
        namespace: flux-system
  interval: 30m
  values:
    controller:
      type: statefulset

    image:
      repository: ghcr.io/navidrome/navidrome
      tag: 0.49.3

    env:
      ND_DATAFOLDER: /data
      ND_ENABLEDOWNLOADS: "true"
      ND_ENABLEEXTERNALSERVICES: "false"
      ND_ENABLESHARING: "false"
      ND_ENABLESTARRATING: "false"
      ND_LOGLEVEL: info
      ND_MUSICFOLDER: /music
      ND_PORT: &port 4533
      ND_SCANSCHEDULE: 30m

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-ext.econline.local
        ingressClassName: "external-nginx"
        hosts:
          - host: &host navidrome-kidseconline.local
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      music-kids:
        enabled: true
        mountPath: /music
        path: /volume1/Media/Library/Kids/Music
        server: synology.econline.local
        type: nfs
        readOnly: true

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      supplementalGroups:
        - 65539

    resources:
      requests:
        cpu: 5m
        memory: 527M
      limits:
        memory: 527M

    volumeClaimTemplates:
      - name: data
        mountPath: /data
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block
