---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./helmrelease.yaml
  - ./volsync.yaml
labels:
  - pairs:
      app.kubernetes.io/name: navidrome-kids
      app.kubernetes.io/instance: navidrome-kids
      app.kubernetes.io/part-of: navidrome
