---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dsmr-reader
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      dsmr-reader:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/xirixiz/dsmr-reader-docker
              tag: 5.11.0-2025.01.02
            env:
              DJANGO_TIME_ZONE: "Europe/Amsterdam"
              DISABLE_NGINX_ACCESS_LOGS: true
              DSMRREADER_OPERATION_MODE: api_server
            envFrom:
              - secretRef:
                  name: dsmr-reader-secret
              - secretRef:
                  name: dsmr-reader-db-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 47m
                memory: 662M
              limits:
                memory: 662M

    service:
      app:
        controller: dsmr-reader
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.1.1.137
        ports:
          http:
            port: 80

    ingress:
      app:
        className: "internal-nginx"
        hosts:
          - host: dsmr-reader.econline.nl
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
