---
log:
  output: "stdout"

streams:
  attic_3d_printer: rtsp://scrypted.home-automation.svc.cluster.local:34136/ffcde3df7d5eb662
  doorbell: rtsp://scrypted.home-automation.svc.cluster.local:34135/8472285c9f0c0dd8
