---
api:
  listen: :80

rtsp:
  listen: :554

webrtc:
  listen: :8555
  candidates:
    - stun:8555
  ice_servers:
    - urls:
        - stun:stun.cloudflare.com:3478

streams:
  entrance_record:
    - rtsp://${go2rtc_username}:${go2rtc_password}@doorbell.home.econline.nl:554/
    - ffmpeg:http://doorbell.home.econline.nl/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=${go2rtc_username}&password=${go2rtc_password}#audio=opus#audio=volume
  entrance_detect:
    - rtsp://${go2rtc_username}:${go2rtc_password}@doorbell.home.econline.nl:554/h264Preview_01_sub
    - ffmpeg:http://doorbell.home.econline.nl/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=${go2rtc_username}&password=${go2rtc_password}#audio=opus#audio=volume
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=25dB"