{
 "title": "Ceph - Cluster Copy",
 "description": "Ceph Cluster overview. copy\r\n",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "cluster", "label": "cluster", "query": "label_values(cluster)" }
  ]
 },
 "panels": [
  { "title": "CLUSTER STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (ceph_health_status{cluster=\"$cluster\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_op_w_in_bytes{cluster=\"$cluster\"}[5m]))"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (ceph_daemon, instance) (irate(ceph_osd_op_r_out_bytes{cluster=\"$cluster\"}[5m]))"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (ceph_cluster_total_bytes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) ((ceph_cluster_total_bytes{cluster=\"$cluster\"}-ceph_cluster_total_used_bytes{cluster=\"$cluster\"})/ceph_cluster_total_bytes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, pool_id) (ceph_pool_objects{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (ceph_osd_op_w_in_bytes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Bytes Read",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (ceph_osd_op_r_out_bytes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{cluster='$cluster',alertstate='firing',alertname=~'^CephCluster.*'}) OR vector(0)"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (ceph_daemon, instance) (irate(ceph_osd_op_w{cluster=\"$cluster\"}[5m]))"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (ceph_daemon, instance) (irate(ceph_osd_op_r{cluster=\"$cluster\"}[5m]))"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (ceph_cluster_total_used_bytes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Mon Session Num",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (ceph_mon_num_sessions{cluster='$cluster'})"
    }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count without (instance, ceph_daemon) (ceph_mon_quorum_status{cluster=\"$cluster\"})"
    }
   ]
  },
  { "title": "OSD STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "OSDs OUT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count without (instance, ceph_daemon) (ceph_osd_up{cluster=\"$cluster\"}) - count without (instance, ceph_daemon) (ceph_osd_in{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{cluster=\"$cluster\"} == 0.0) OR vector(0)"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (ceph_osd_up{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "OSDs IN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (ceph_osd_in{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Avg PGs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (instance, ceph_daemon) (ceph_osd_numpg{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Avg Apply Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (instance, ceph_daemon) (ceph_osd_apply_latency_ms{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Avg Commit Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Avg Op Write Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (instance, ceph_daemon) (rate(ceph_osd_op_w_latency_sum{cluster=\"$cluster\"}[5m]) / rate(ceph_osd_op_w_latency_count{cluster=\"$cluster\"}[5m]) >= 0)"
    }
   ]
  },
  {
   "title": "Avg  Op Read Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (instance, ceph_daemon) (rate(ceph_osd_op_r_latency_sum{cluster=\"$cluster\"}[5m])/rate(ceph_osd_op_r_latency_count{cluster=\"$cluster\"}[5m]) >= 0)"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alerts from CephThanos",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "ALERTS{cluster='$cluster', alertstate='firing'}"
      }
     ]
    },
    {
     "title": "Top Sluggish OSD's",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
     "targets": [
      {
       "expr": "topk(5,sort_desc(ceph_osd_apply_latency_ms{cluster='$cluster'} + ceph_osd_commit_latency_ms{cluster='$cluster'}))"
      }
     ]
    },
    {
     "title": "Down OSD's",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
     "targets": [
      {
       "expr": "ceph_osd_up{cluster=\"$cluster\"} == 0"
      }
     ]
    }
   ]
  },
  {
   "title": "Ceph Versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ceph OSD Versions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (ceph_version) (ceph_osd_metadata{cluster='$cluster'})",
       "legendFormat": "{{ ceph_version }}"
      }
     ]
    },
    {
     "title": "Ceph Mon Versions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_mon_metadata{cluster='$cluster'})",
       "legendFormat": "{{ ceph_version }}"
      }
     ]
    },
    {
     "title": "Ceph MDS Versions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_mds_metadata{cluster='$cluster'})",
       "legendFormat": "{{ ceph_version }}"
      }
     ]
    },
    {
     "title": "Ceph RGW Versions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_rgw_metadata{cluster='$cluster'})",
       "legendFormat": "{{ ceph_version }}"
      }
     ]
    }
   ]
  },
  { "title": "CLUSTER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) (ceph_cluster_total_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Total Capacity"
    },
    {
     "expr": "sum without (instance) (ceph_cluster_total_bytes{cluster=\"$cluster\"}-ceph_cluster_total_used_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum without (instance) (ceph_cluster_total_used_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_op_w{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_op_r{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_op_w_in_bytes{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_op_r_out_bytes{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Pool Bytes Recovered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum((ceph_pool_num_bytes_recovered{cluster='$cluster'}) *on (instance, pool_id) group_left(name)(ceph_pool_metadata{cluster='$cluster'})) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Objects Recovered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, pool_id) ((ceph_pool_num_objects_recovered{cluster='$cluster'}) *on (instance, pool_id) group_left(name)(ceph_pool_metadata{cluster='$cluster'}))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Objects Per Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) ((ceph_pool_objects{cluster='$cluster'}) *on (instance, pool_id) group_left(name)(ceph_pool_metadata{cluster='$cluster'}))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Quota Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) ((ceph_pool_quota_bytes{cluster='$cluster'}) *on (instance, pool_id) group_left(name)(ceph_pool_metadata{cluster='$cluster'}))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Objects Quota",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) (ceph_pool_quota_objects{cluster='$cluster'}) *on (instance, pool_id) group_left(name)(ceph_pool_metadata{cluster='$cluster'})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "OSD Type Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count without (instance, ceph_daemon) (ceph_bluestore_commit_lat_count{cluster='$cluster'})",
     "legendFormat": "BlueStore"
    },
    {
     "expr": "count without (instance, ceph_daemon) (ceph_filestore_journal_latency_count{cluster='$cluster'})",
     "legendFormat": "FileStore"
    }
   ]
  },
  { "title": "OBJECTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Objects in the Cluster",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, pool_id) (ceph_pool_objects)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "PGs State",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_active{cluster=\"$cluster\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_clean{cluster=\"$cluster\"})",
     "legendFormat": "Clean"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_peering{cluster=\"$cluster\"})",
     "legendFormat": "Peering"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_degraded{cluster=\"$cluster\"})",
     "legendFormat": "Degraded"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_stale{cluster=\"$cluster\"})",
     "legendFormat": "Stale"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_unclean_pgs{cluster=\"$cluster\"})",
     "legendFormat": "Unclean"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_undersized{cluster=\"$cluster\"})",
     "legendFormat": "Undersized"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_incomplete{cluster=\"$cluster\"})",
     "legendFormat": "Incomplete"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_forced_backfill{cluster=\"$cluster\"})",
     "legendFormat": "Forced Backfill"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_inconsistent{cluster=\"$cluster\"})",
     "legendFormat": "Inconsistent"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_forced_recovery{cluster=\"$cluster\"})",
     "legendFormat": "Forced Recovery"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_creating{cluster=\"$cluster\"})",
     "legendFormat": "Creating"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_wait_backfill{cluster=\"$cluster\"})",
     "legendFormat": "Wait Backfill"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_deep{cluster=\"$cluster\"})",
     "legendFormat": "Deep"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_scrubbing{cluster=\"$cluster\"})",
     "legendFormat": "Scrubbing"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_recovering{cluster=\"$cluster\"})",
     "legendFormat": "Recovering"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_repair{cluster=\"$cluster\"})",
     "legendFormat": "Repair"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_down{cluster=\"$cluster\"})",
     "legendFormat": "Down"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_peered{cluster=\"$cluster\"})",
     "legendFormat": "Peered"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_backfill{cluster=\"$cluster\"})",
     "legendFormat": "Backfill"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_remapped{cluster=\"$cluster\"})",
     "legendFormat": "Remapped"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_backfill_toofull{cluster=\"$cluster\"})",
     "legendFormat": "Backfill Toofull"
    }
   ]
  },
  {
   "title": "Stuck PGs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_degraded{cluster=\"$cluster\"})",
     "legendFormat": "Degraded"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_stale{cluster=\"$cluster\"})",
     "legendFormat": "Stale"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_undersized{cluster=\"$cluster\"})",
     "legendFormat": "Undersized"
    }
   ]
  },
  {
   "title": "Recovery Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_recovery_ops{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "OPS"
    }
   ]
  },
  { "title": "LATENCY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "OSD Apply Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "ceph_osd_apply_latency_ms{cluster='$cluster'}"
    }
   ]
  },
  {
   "title": "OSD Commit Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "ceph_osd_commit_latency_ms{cluster='$cluster'}"
    }
   ]
  },
  {
   "title": "OSD Read Op Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r_latency_sum{cluster=\"$cluster\"}[5m]) / rate(ceph_osd_op_r_latency_count{cluster=\"$cluster\"}[5m]) >= 0"
    }
   ]
  },
  {
   "title": "OSD Write Op Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_w_latency_sum{cluster=\"$cluster\"}[5m]) / rate(ceph_osd_op_w_latency_count{cluster=\"$cluster\"}[5m]) >= 0"
    }
   ]
  },
  {
   "title": "Avg OSD  Op  Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg without (instance,ceph_daemon) (rate(ceph_osd_op_r_latency_sum{cluster=\"$cluster\"}[5m]) / rate(ceph_osd_op_r_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "read"
    },
    {
     "expr": "avg without (instance, ceph_daemon) (rate(ceph_osd_op_w_latency_sum{cluster=\"$cluster\"}[5m]) / rate(ceph_osd_op_w_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "AVG OSD Apply + Commit Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg without (instance, ceph_daemon) (ceph_osd_apply_latency_ms{cluster=\"$cluster\"})",
     "legendFormat": "apply"
    },
    {
     "expr": "avg without (instance, ceph_daemon) (ceph_osd_commit_latency_ms{cluster=\"$cluster\"})",
     "legendFormat": "commit"
    }
   ]
  },
  { "title": "Node Statistics (NodeExporter)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Node Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_anon_bytes{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum without (instance) (node_memory_Active_anon_bytes{cluster='$cluster'})",
     "legendFormat": "Cluster Memory Usage"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (irate(node_cpu_seconds_total{cluster='$cluster',mode!=\"idle\"}[$interval])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_disk_read_bytes_total{cluster='$cluster'}[$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node In",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_disk_written_bytes_total{cluster='$cluster'}[$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Free Space in root filesystem",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_free_bytes{cluster=\"$cluster\", mountpoint='/', device != 'rootfs'})*100 / (node_filesystem_size_bytes{cluster=\"$cluster\", mountpoint='/', device != 'rootfs'})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}