---
# TODO: add schema
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: context7-mcp
spec:
  groupRef:
    name: mcp-tools
  image: ghcr.io/stacklok/dockyard/npx/context7:3.2.2@sha256:541bfbfb5819aed74668eec4c5ce91eea62d7e986016e0a0b25e6825967910ae
  secrets:
    - name: context7-mcp-secret
      key: api_key
      targetEnvName: CONTEXT7_API_KEY
  transport: stdio
