---
# TODO: add schema
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: context7-mcp
spec:
  groupRef:
    name: mcp-tools
  image: ghcr.io/stacklok/dockyard/npx/context7:3.2.4@sha256:a3c75d5b94aea84a2c553b2b3f2b4417639239b0a63ecd9ea456ec008307cb68
  secrets:
    - name: context7-mcp-secret
      key: api_key
      targetEnvName: CONTEXT7_API_KEY
  transport: stdio
