---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
data:
  DB_DATABASE_NAME: immich
  DB_HOSTNAME: immich-database-postgres.media.svc.cluster.local.
  DB_PORT: "5432"
  REDIS_HOSTNAME: immich-database-valkey.media.svc.cluster.local.
  REDIS_PORT: "6379"
  UPLOAD_LOCATION: /data
