---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v11
kind: Kustomization
namespace: flux-system
resources:
  - ./helmrelease.yaml
  - ./secret.sops.yaml
