apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops
    namespace: flux-system
stringData:
    adminPassword: ENC[AES256_GCM,data:KVbailsjN3Q8xn4dpumo9yMuA8+/rKNH6IMkRl4od4V++H0kW3ZZnCpBi9+4C5GUAo2ZSEQxD9raRj6N,iv:Xh++g7+wO528IGWH9t/wPn6uxGar8ZZWYVpa+Ik/nAI=,tag:ZFl8FbIIZ3zUr9CW78f3mw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mtzvncgylzrqrf3m6e4wpxt8sk6zq59mdraehr7lhxksyltmwdksl0ltrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMy9yV21nSjVJMmNFYUlo
            TWlrOVptWWYyc3BlcytMUkxGWE5Wb293VENBCithbmVSQmUwZDdWNmY4b3FJeVRp
            Zy9oQk5lYUFKcXpQZkVBTjAxdkp0VzAKLS0tIFVJMy9wajRXZ0EvVDF4akJCUVJL
            TmF3WGl5YXhNOE0yWmNzc3ZsSFMyY0EKTXGCw6+gNgoCHVeWkFHWx1kMn2t8YBD6
            RD/Is/W4hVMG9vYkDB/a5fqu5CR1JvSYrCOfXhAx1t33pBAxRVq59w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-28T22:14:53Z"
    mac: ENC[AES256_GCM,data:KOjidtcZM635InU0H4nSY73o4yUGpxAjnf3p/r486+BrXteVHFhaEVcafk4zCrh5scBXMeoCYsOjoQtasB4BqRyNlAD1FZ742Li59KyR/O9QTWisc1TIhhJwelRBaAPqYrsbudKQ2E1W9YtY8z+oL5T/vWnHCJ+4/SNx3Ei7tAw=,iv:OElWmHektI553YPwxxugLU8iseqhMN0LDDLfUmdu0so=,tag:DuKKuWFx4RrGnLmTAJDW+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
