---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: lan-icmp
spec:
  module: icmp
  prober:
    url: blackbox-exporter-lan.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - office-jetkvm.home.econline.nl
        - office-zigbee-adapter.home.econline.nl
        - living-vacuum.home.econline.nl
        - hallway-velux-gateway.home.econline.nl
        # - delta.home.econline.nl # Enable when the device is back online
        - enigma.home.econline.nl
        - felix.home.econline.nl
        - gladius.home.econline.nl
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter-lan
      action: replace
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: lan-tcp
spec:
  module: tcp_connect
  prober:
    url: blackbox-exporter-lan.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - gladius.home.econline.nl:2049
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter-lan
      action: replace
