---
# Note: Authelia vars should be escaped with $${VAR_NAME} to avoid interpolation by Flux
log:
  level: 'debug'

authentication_backend:
  password_reset:
    disable: true
  refresh_interval: 1m
  ldap:
    address: ldap://lldap.security.svc.cluster.local:389
    implementation: custom
    timeout: 5s
    start_tls: false
    base_dn: dc=econline,dc=nl
    additional_users_dn: ou=people
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (member={dn})
    group_search_mode: filter
    user: "{{ .lldap_user_dn }}"
    password: "{{ .lldap_ldap_password }}"
    attributes:
      username: uid
      display_name: displayName
      mail: mail
      member_of: memberOf
      group_name: cn

session:
  secret: "{{ .authelia_session_secret }}"
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - name: econline_nl_session
      domain: econline.nl
      authelia_url: https://auth.econline.nl
      default_redirection_url: https://econline.nl
  redis:
    host: dragonfly.database.svc.cluster.local
    database_index: 1

storage:
  encryption_key: "{{ .authelia_storage_encryption_key }}"

notifier:
  #disable_startup_check: true
  smtp:
    username: "{{ .authelia_notifier_smtp_username }}"
    password: "{{ .authelia_notifier_smtp_password }}"
    address: "smtp://smtp.gmail.com:587"
    sender: "{{ .authelia_notifier_smtp_username }}"
    subject: "[Authelia] {title}"

totp:
  disable: false
  issuer: authelia.com

webauthn:
  disable: false
  display_name: 'Authelia'
  attestation_conveyance_preference: 'indirect'
  user_verification: 'preferred'
  timeout: '60s'

duo_api:
  disable: true

access_control:
  default_policy: deny
  networks:
    - name: internal
      networks:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
  rules:
    - domain:
        - echo-server.econline.nl
      subject:
        - ["user:erik"]
      policy: two_factor
    - domain:
        - sabnzbd-cees.econline.nl
        - files-cees.econline.nl
      subject:
        - ["user:cees"]
      policy: one_factor
      

identity_validation:
  reset_password:
    jwt_secret: "{{ .authelia_jwt_secret }}"

identity_providers:
  oidc:
    hmac_secret: "{{ .authelia_oidc_hmac_secret }}"
    cors:
      endpoints: ["authorization", "token", "revocation", "introspection"]
      allowed_origins_from_client_redirect_uris: true
    jwks:
      - key: |-
          {{- .authelia_oidc_issuer_key | nindent 10 }}
        algorithm: 'RS256'
    clients:
      - client_id: "{{ .grafana_oauth_client_id }}"
        client_name: Grafana
        client_secret: "{{ .grafana_oauth_client_secret }}"
        public: false
        authorization_policy: one_factor
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris:
          - https://grafana.econline.nl/login/generic_oauth
        userinfo_signed_response_alg: none
