---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homepage-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        HOMEPAGE_VAR_HOME_LATITUDE: "{{ .homepage_latitude }}"
        HOMEPAGE_VAR_HOME_LONGITUDE: "{{ .homepage_longitude }}"
        HOMEPAGE_VAR_RADARR_KEY: "{{ .radarr_api_key }}"
        HOMEPAGE_VAR_SONARR_KEY: "{{ .sonarr_api_key }}"
  dataFrom:
    - extract:
        key: homepage
      rewrite:
        - regexp:
            source: "(.*)"
            target: "homepage_$1"
    - extract:
        key: radarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "radarr_$1"
    - extract:
        key: sonarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sonarr_$1"
