---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-dsmr-reader
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/cluster-0/apps/home-automation/dsmr-reader/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false # no flux ks dependents
  dependsOn:
    - name: cluster-apps-ext-postgres-operator
    - name: cluster-apps-external-secrets-stores
