---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Amsterdam"
  KUBE_VIP_ADDR: "192.168.0.20"
  METALLB_LB_RANGE: "192.168.0.70-192.168.0.79"
  METALLB_K8S_GATEWAY_ADDR: "192.168.0.70"
  METALLB_INGRESS_ADDR: "192.168.0.71"
