---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: echo-server
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/mendhak/http-https-echo
      tag: "30"

    env:
      HTTP_PORT: &port 8080
      LOG_WITHOUT_NEWLINE: "true"
      LOG_IGNORE_PATH: "/healthz"

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          # nginx.ingress.kubernetes.io/auth-url: http://authelia.security.svc.cluster.local/api/verify
          # nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}?rm=$request_method
          nginx.ingress.kubernetes.io/auth-response-headers: "Remote-User,Remote-Name,Remote-Groups,Remote-Email"
          external-dns.alpha.kubernetes.io/hostname: "{{ .Release.Name }}.${SECRET_DOMAIN}"

        hosts:
          - host: &host "echo-server.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    resources:
      requests:
        cpu: 5m
        memory: 30M
      limits:
        memory: 30M