---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: kireque
        namespace: flux-system
  interval: 30m
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/onedr0p/plex
      tag: 1.32.5.7328-2632c9d3a@sha256:cdcf7d87f96a810d8af75ad58e1f0b0bdcc761de9b829f2473f7a17e7c67c241

    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: "10.45.0.20"
        ports:
          http:
            port: 32400

    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-exteconline.local
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        ingressClassName: "external-nginx"
        hosts:
          - host: &host plexeconline.local
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      nfs-nas-media:
        enabled: true
        mountPath: /storage/media
        path: /volume1/Media
        server: synology.econline.local
        type: nfs
      transcode:
        enabled: true
        type: emptyDir

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 65539

    nodeSelector:
      intel.feature.node.kubernetes.io/gpu: "true"

    resources:
      requests:
        cpu: 100m
        gpu.intel.com/i915: 1
        memory: 9248M
      limits:
        gpu.intel.com/i915: 1
        memory: 9248M

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 20Gi
        storageClass: ceph-block
