# yaml-language-server: $schema=https://gist.githubusercontent.com/james-d-elliott/756de37a4398b3445072a60d674905c6/raw/ce90833b1ce145cb701184557dd964fa7546f19a/jsonschema.json
---
storage:
  encryption_key: a_very_important_secret
  local:
    path: /config/db.sqlite3

access_control:
  default_policy: deny
  networks:
    - name: internal
      networks:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
  rules:
    - domain:
        - echo-server.${SECRET_DOMAIN}
      policy: one_factor
      subject:
        - ["group:admins"]

    - domain:
        - "calibre-web.${SECRET_DOMAIN}"
      policy: one_factor
      subject:
        - ["group:calibreweb"]

    - domain:
        - "bookmarks.${SECRET_DOMAIN}"
      resources:
        - "^/api/.*$"
      policy: bypass
    - domain:
        - "bookmarks.${SECRET_DOMAIN}"
      policy: two_factor
      subject:
        - ["group:admins"]

identity_providers:
  oidc:
    cors:
      endpoints:
        - "authorization"
        - "token"
        - "revocation"
        - "introspection"
      allowed_origins_from_client_redirect_uris: true
    clients:
      - id: grafana
        description: Grafana
        secret: "${GRAFANA_OAUTH_CLIENT_SECRET}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes:
          - "openid"
          - "profile"
          - "groups"
          - "email"
        redirect_uris:
          - "https://grafana.${SECRET_DOMAIN}/login/generic_oauth"
        userinfo_signing_algorithm: none
    #   - id: miniflux
    #     description: Miniflux
    #     secret: "${MINIFLUX_OAUTH_CLIENT_SECRET}"
    #     public: false
    #     authorization_policy: one_factor
    #     pre_configured_consent_duration: 1y
    #     scopes:
    #       - "openid"
    #       - "profile"
    #       - "groups"
    #       - "email"
    #     redirect_uris:
    #       - "https://miniflux.bjw-s.dev/oauth2/oidc/callback"
    #     userinfo_signing_algorithm: none
    #   - id: nodered
    #     description: Node-RED
    #     secret: "${NODERED_OAUTH_CLIENT_SECRET}"
    #     public: false
    #     authorization_policy: two_factor
    #     scopes:
    #       - openid
    #       - groups
    #       - email
    #       - profile
    #     redirect_uris:
    #       - https://nodered.bjw-s.dev/auth/strategy/callback
    #     userinfo_signing_algorithm: none
    #   - id: immich
    #     description: Immich
    #     secret: "${IMMICH_OAUTH_CLIENT_SECRET}"
    #     public: false
    #     authorization_policy: one_factor
    #     pre_configured_consent_duration: 1y
    #     scopes:
    #       - "openid"
    #       - "profile"
    #       - "email"
    #     redirect_uris:
    #       - "https://immich.bjw-s.dev/auth/login"
    #       - "app.immich:/"
    #     userinfo_signing_algorithm: none
    #   - id: windmill
    #     description: Windmill
    #     secret: "${WINDMILL_OAUTH_CLIENT_SECRET}"
    #     public: false
    #     authorization_policy: two_factor
    #     pre_configured_consent_duration: 1y
    #     scopes:
    #       - "openid"
    #       - "profile"
    #       - "email"
    #     redirect_uris:
    #       - "https://windmill.bjw-s.dev/user/login_callback/authelia"
    #     userinfo_signing_algorithm: none