---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-oauth2-proxy-redis
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/cluster-0/apps/security/oauth2-proxy/redis"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-external-secrets-stores
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-oauth2-proxy
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/cluster-0/apps/security/oauth2-proxy/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-oauth2-proxy-redis
    - name: cluster-apps-external-secrets-stores
