---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: go2rtc
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: go2rtc-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: go2rtc
      rewrite:
        - regexp:
            source: "(.*)"
            target: "go2rtc_$1"
