---
ansible_host: "10.1.1.11"
ansible_python_interpreter: /volume1/@appstore/python310/bin/python3

certificates:
  - common_name: "*econline.local"
    email: "postmaster@bjw-s.dev"
  - common_name: "*.bjw-s.tech"
    email: "postmaster@bjw-s.tech"

apps:
  syno_cli:
    image_repository: ghcr.io/reddec/syno-cli
    # renovate: datasource=docker depName=ghcr.io/reddec/syno-cli
    image_tag: "0.1.3"
    data_folder: /volume1/docker/syno_cli

  minio:
    image_repository: quay.io/minio/minio
    # renovate: datasource=docker depName=quay.io/minio/minio
    image_tag: RELEASE.2023-07-18T17-49-40Z
    data_folder: /volume1/docker/minio/data

  node_exporter:
    image_repository: quay.io/prometheus/node-exporter
    # renovate: datasource=docker depName=quay.io/prometheus/node-exporter
    image_tag: v1.6.0
