ansible_user: ENC[AES256_GCM,data:zeB61w0kvgfZ0p8=,iv:xfGzTCx138+qS+tyzOgJ+EDPoetmn9LTznwtKi5ukNQ=,tag:mFqrjiOBzFAt9NblHUvORQ==,type:str]
syno_cli:
    user: ENC[AES256_GCM,data:qM6O44T2zxWnWy4=,iv:Es3Nyz/Mzz5+qCNkUMuDpGpjomXxLSkxtJsQULZkTtc=,tag:LzI48x+Dw2xdKRGCrZgmLQ==,type:str]
    password: ENC[AES256_GCM,data:6ynV9Sj+cRFv4hKaoW0OphjS3uBkmQ+vd2w=,iv:aaOP+qtV5hc9UoVujBSo1XoqIEG2LQZN5g7TGL5YI50=,tag:xiTX15r/brlhJcVw/nvtWA==,type:str]
    cloudflare_token: ENC[AES256_GCM,data:lksrRES1+IDSgw5Tv4C+tYV1wbj8jfG+TMFrNhEDOPxCepjl9wU/rA==,iv:myOWdsz1fwwzJenO3FNOrDpUfRikbtaBzCjFetbjt4s=,tag:PGOB6p9IIhiq2rOjd/Zv+w==,type:str]
secrets:
    autoscan:
        plex_token: ENC[AES256_GCM,data:lR8Fh4dTmYFdoKb4n50DBa6do+s=,iv:H40Lmd2Hfcw35Ib8rPGvgMj4gRPcmmUNUdidVyfX7co=,tag:Iyo34JUU8/oYxFyM88/jfA==,type:str]
        jellyfin_token: ENC[AES256_GCM,data:1Jv2K7uYo5u5cltex40WAmidam5UPGWg5OsADxH5vdc=,iv:HAqSUXW5CtKQ7k9xLkaTJ94Y9UjGcEQvYzuwb0A74hs=,tag:v88tfqOLSSgmsqvBsYEo3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uk0y2ahfavgsgqvrtg5a22w5gytpdmjuatxtcw6kntmxhlcgreesuwzw5s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVWJjOGNLSUh0RWJTNVlL
            V0R6RFdpV3JoWW9oQ042UmhMTlNFdEhRM0ZzClEyV3gySVVlTDR0a3pjODZPekZX
            QmZVOVltNTFya29jWnlrMTZqUU1HZ3MKLS0tIDVQTi9TaGtIQkNUZk5OR2VRTTBV
            MmJ0S2lFQjI2OXZFL01aZ2dqanVRWFUK2H5XNWeuxiWkiSk28byqXN7Bw1bxmtR5
            d1Gjbw85N6e3RvOfhXDC0dTwh1ZWoFrNgw71V4CFVzeKOA63usN/YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-19T19:27:22Z"
    mac: ENC[AES256_GCM,data:pbnL2FOWiITSks+9704JKKyDazuTcb6y3UUEV5kqI2xHr4PGac5TxRyZtHIMZOLhjBTvGheQrqGwShqWsI+Oz/tsy+DxCxrPQOs+qwtG8HSBtIOPEwge8HiSTGtYmDBVvOXbDMV0R6LyhYidsn5RQ4baq5vvx7tqFji2IEelvkQ=,iv:UNpJXi0hRZa2gOb3+2MuhJz6op4WOzpx2u/AfZuO1E8=,tag:posZJcCJg66VpMxPBrZorg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
