---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/onedr0p/sonarr-develop
      tag: 4.0.0.657@sha256:7cad79cd0c852ac74c0f8088235bcd8ed50623db10090d38be680db31c4183d0

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    env:
      SONARR__INSTANCE_NAME: Sonarr
      SONARR__PORT: &port 8989
      SONARR__AUTHENTICATION_METHOD: External
      SONARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
      SONARR__APPLICATION_URL: "https://sonarr.${SECRET_DOMAIN}"
      SONARR__LOG_LEVEL: info
      SONARR__API_KEY: testtesttesttesttest

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "sonarr.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
        annotations:
          hajimari.io/icon: mdi:sonarr
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads
          gethomepage.dev/icon: "sonarr"
          gethomepage.dev/name: "sonarr"
          gethomepage.dev/widget.type: "sonarr"
          gethomepage.dev/widget.url: "http://sonarr.downloads.svc.cluster.local:9696"
          gethomepage.dev/widget.key: "testtesttesttesttest"
          gethomepage.dev/podSelector: ""

    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
      media:
        enabled: true
        existingClaim: nas-media
        mountPath: /data/nas-media

    resources:
      requests:
        cpu: 20m
        memory: 323M
      limits:
        memory: 323M