---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: recyclarr
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    initContainers:
      01-init-config:
        image: public.ecr.aws/docker/library/busybox:latest@sha256:3fbc632167424a6d997e74f52b878d7cc478225cffac6bc977eedfe51c7f4e79
        imagePullPolicy: IfNotPresent
        command:
          - "/bin/sh"
          - "-c"
          - "cp /tmp/config/recyclarr.yaml /config/recyclarr.yaml"
        volumeMounts:
          - name: config-file
            mountPath: /tmp/config
          - name: config
            mountPath: /config

    restartPolicy: OnFailure

    image:
      repository: ghcr.io/recyclarr/recyclarr
      tag: 5.4.0@sha256:2819a8722116225db1101d94fd6c9ccaa8b30ad95e0c969a7459a03e21bf011b

    # envFrom:
    #   - secretRef:
    #       name: recyclarr-secret

    persistence:
      config-file:
        enabled: true
        type: configMap
        name: recyclarr-configmap
        mountPath: "-"

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch

    resources:
      requests:
        cpu: 5m
        memory: 36M
      limits:
        memory: 128M

    service:
      main:
        enabled: false

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block