---
# TODO: add schema
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: ha-mcp
spec:
  env:
    - name: HOMEASSISTANT_URL
      value: http://home-assistant.home-automation.svc.cluster.local:8123
  groupRef:
    name: mcp-tools
  image: ghcr.io/homeassistant-ai/ha-mcp:7.6.0@sha256:c6d5e0f65d5d2bec4be54f273c8bbe4eeaeb46460d27e5a63ba7bc865b864ce0
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          command:
            - ha-mcp-web
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      volumes:
        - name: tmp
          emptyDir: {}
  secrets:
    - name: ha-mcp-secret
      key: HOMEASSISTANT_TOKEN
  transport: streamable-http
