---
ingress:
  - hostname: "econline.nl"
    service: https://nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: ingress-ext.econline.nl
  - hostname: "*.econline.nl"
    service: https://nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: ingress-ext.econline.nl
  - service: http_status:404
