---
originRequest:
  originServerName: ingress-ext.econline.nl

ingress:
  - hostname: econline.nl
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.econline.nl"
    service: *svc
  - service: http_status:404
