---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app frigate
  namespace: &namespace home-automation
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  timeout: 5m
  path: ./kubernetes/apps/home-automation/frigate/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
    - name: multus-networks
      namespace: network
    - name: onepassword-store
      namespace: external-secrets
    - name: volsync
      namespace: system
    - name: keda
      namespace: system
  components:
    - ../../../../components/volsync
    - ../../../../components/keda/nas-nfs-scaler
  retryInterval: 1m
  postBuild:
    substitute:
      APP: *app
      CAPACITY: 2Gi
