---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: frigate
spec:
  components:
    - ../../../../components/gpu
    - ../../../../components/kopiur/backup
    - ../../../../components/nfs-scaler
  targetNamespace: home-automation
  path: ./kubernetes/apps/home-automation/frigate/app
  interval: 1h
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: intel-gpu-resource-driver
      namespace: kube-system
    - name: multus-networks
      namespace: kube-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
  postBuild:
    substitute:
      APP: frigate
      KOPIUR_CAPACITY: 5Gi
      KOPIUR_IGNORE_RULES: "[.jwt_secret]"
