---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname frigate
  namespace: &namespace home-automation
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: multus-networks
      namespace: network
    - name: onepassword-store
      namespace: external-secrets
    - name: volsync
      namespace: system
  interval: 1h
  timeout: 5m
  path: "./kubernetes/apps/home-automation/frigate/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: false
  postBuild:
    substitute:
      APP: *appname
      VOLSYNC_CLAIM: frigate-config
      VOLSYNC_CAPACITY: 5Gi
