---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      sabnzbd:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            runAsNonRoot: true
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 65542 # gladius:external-services

        containers:
          sabnzbd:
            image:
              repository: ghcr.io/onedr0p/sabnzbd
              tag: 4.4.1@sha256:8a415c665b1a03ae5d19e436586ceb772d8144f2290cbe2ba6cbdeedec8b6801
            env:
              SABNZBD__PORT: &sabnzbdport 8080
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd-cees,
                sabnzbd-cees.family,
                sabnzbd-cees.family.svc,
                sabnzbd-cees.family.svc.cluster,
                sabnzbd-cees.family.svc.cluster.local,
                sabnzbd-cees.econline.nl
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 5m
                memory: 1024Mi
              limits:
                memory: 6144Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

          # Configure the filebrowser sidecar
          filebrowser:
            dependsOn: sabnzbd
            image:
              repository: docker.io/filebrowser/filebrowser
              tag: v2.31.2@sha256:a4da9ca8364b0a1fc5dd36f7add92582bf673c0ae0bda8dd9bd13062c41d1715
            env:
              FB_DATABASE: /config/filebrowser.db
              FB_ROOT: /data
              FB_LOG: stdout
              FB_NOAUTH: true
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 8Gi

    service:
      sabnzbd:
        controller: sabnzbd
        ports:
          http:
            port: *sabnzbdport

      filebrowser:
        controller: sabnzbd
        ports:
          http:
            port: 80

    ingress:
      sabnzbd:
        className: "external-nginx"
        annotations:
          nginx.ingress.kubernetes.io/auth-method: GET
          nginx.ingress.kubernetes.io/auth-url: https://auth.econline.nl/api/verify
          nginx.ingress.kubernetes.io/auth-signin: https://auth.econline.nl/?rm=$request_method
          nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
          nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Method $request_method;
        hosts:
          - host: &hostSabnzbd sabnzbd-cees.econline.nl
            paths:
              - path: /
                service:
                  identifier: sabnzbd
                  port: http
        tls:
          - hosts:
              - *hostSabnzbd

      filebrowser:
        className: "external-nginx"
        annotations:
          nginx.ingress.kubernetes.io/auth-method: GET
          nginx.ingress.kubernetes.io/auth-url: https://auth.econline.nl/api/verify
          nginx.ingress.kubernetes.io/auth-signin: https://auth.econline.nl/?rm=$request_method
          nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
          nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Method $request_method;
        hosts:
          - host: &hostFilebrowser files-cees.econline.nl
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: filebrowser
                  port: http
        tls:
          - hosts:
              - *hostFilebrowser

    persistence:
      config:
        existingClaim: family-sabnzbd-config
        globalMounts:
          - path: /config

      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 100Gi
        globalMounts:
          - path: /data

      temp:
        type: emptyDir
        globalMounts:
          - path: /tmp
