---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    ---
  docker.yaml: |
    ---
  kubernetes.yaml: |
    ---
    mode: cluster

  services.yaml: |
    ---
    - Media:
        - Jellyfin:
            icon: jellyfin.png
            href: https://jellyfin.${SECRET_DOMAIN}
            description: Media Server
            widget:
              type: jellyfin
              url: http://jellyfin.media.svc.cluster.local:8096
              key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
              enableNowPlaying: true
        - Radarr:
            icon: radarr.png
            href: https://radarr.${SECRET_DOMAIN}
            description: Movies Management
            widget:
              type: radarr
              url: http://radarr.downloads.svc.cluster.local:7878
              key: {{HOMEPAGE_VAR_RADARR_KEY}}
        - Sonarr:
            icon: sonarr.png
            href: https://sonarr.${SECRET_DOMAIN}
            description: TV Shows Management
            widget:
              type: sonarr
              url: http://sonarr.downloads.svc.cluster.local:8989
              key: {{HOMEPAGE_VAR_SONARR_KEY}}
    - Favorites:
        - My GitHub Repo:
            icon: si-github
            href: https://github.com/kireque
            description: My Code Repository
        - Grafana Dashboard:
            icon: si-grafana
            href: https://grafana.${SECRET_DOMAIN}
            description: My Cluster Metrics Visualization
        - k8s-at-home-search:
            icon: si-kubernetes
            href: https://nanne.dev/k8s-at-home-search/
            description: Search KAH HelmReleases
        - bjw-s home-ops:
            icon: si-github
            href: https://github.com/bjw-s/home-ops
            description: bjw-s HomeOps Repository
        - bjw-s Chart Values:
            icon: si-github
            href: https://github.com/bjw-s/helm-charts/tree/main/charts/library/common#values
            description: app-template Helm Chart Values
    - Kubernetes:
        - Hubble UI:
            icon: cilium
            href: https://hubble-cluster-0.${SECRET_DOMAIN}/
            description: Hubble UI

  settings.yaml: |
    ---
    title: My Personal Home Dashboard
    theme: dark
    color: slate
    headerStyle: clean
    target: _blank
    layout:
      Media:
        style: row
        columns: 4
      Network:
        style: row
      Favorites:
        style: row
        columns: 3
    quicklaunch:
      searchDescription: true
      hideInternetSearch: true
      hideVisitURL: true

  widgets.yaml: |
    ---
    - search:
        provider:
          - google
          - duckduckgo
    - openmeteo:
        label: Home
        latitude: {{HOMEPAGE_VAR_HOME_LATITUDE}}
        longitude: {{HOMEPAGE_VAR_HOME_LONGITUDE}}
        units: metric
        cache: 5
    - openmeteo:
        label: Shop
        latitude: {{HOMEPAGE_VAR_SHOP_LATITUDE}}
        longitude: {{HOMEPAGE_VAR_SHOP_LONGITUDE}}
        units: metric
        cache: 5
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: home-ops-cluster
        nodes:
          show: true