apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
    namespace: default
stringData:
    HOMEPAGE_VAR_HOME_LATITUDE: ENC[AES256_GCM,data:abzX8Vac70HV,iv:ZHVLkzOv5eLyY7xh+gmQyShPdwSiN8OPXhI/0DShdvw=,tag:dcit9HP7SO42Xk2bYJQ28Q==,type:str]
    HOMEPAGE_VAR_HOME_LONGITUDE: ENC[AES256_GCM,data:CEFHfOsSLA==,iv:UQOV2/DB1Frf9TFpFQfJdl5/s6RHbQxMlkSDl5LLFeM=,tag:0AWEzq6PcER3P+W7EjkanA==,type:str]
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:R0GtPExaYmHBaf4=,iv:Sccbrt7ZfiOaaeopaivMki7qen1JRS76Q+aurKn0Bjs=,tag:JyxXocr1q5pmnrdy4vaOCA==,type:str]
    HOMEPAGE_VAR_OMBI_KEY: ENC[AES256_GCM,data:EZW1g6MfRz0AHhg=,iv:97E5I4wulmoRzEmCAbXUa+beCaIYqbL1vAfZmi6NsKg=,tag:1bW8IWlgVfEmw4Y79bU77A==,type:str]
    HOMEPAGE_VAR_IMMICH_KEY: ENC[AES256_GCM,data:KGP7wFuCAMkZR9Y=,iv:og+J8HJWkMNBKxEXNu+NjExL/ASMnBw1ZgjoVq99QsM=,tag:69PYgaG/8oEYr+O4cC8Q5g==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:rfxwo1YCOVdHsxo=,iv:MqDSCr0S2y0gCMYX0sCKGRpho8z2vTMYNfUUL7Tykog=,tag:6MG1lZNItNTVA0d26JMQvw==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:mjzzs2cOoWdaSXg=,iv:78n1kg0YuG/+J+qbh9Qj+10nBfkHFzreZfLYzMXcnRQ=,tag:FRORlp7ioeSqBBCc/mqxfg==,type:str]
    HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:DXIFkqugfY3zEi4=,iv:1lwK1HU1jzMETPeWPcYz5x1ge/We20++TH6if/EYL/U=,tag:/GZT0+RAaZJ9Y5qmnSL7IQ==,type:str]
    HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:uOboYC6pEhOqL18=,iv:sEmrBmoBZCzNKoX03ThG73G0m3DKRdDJ32yq+NijfAg=,tag:cWacgQeMv7mSHbmd6yKCOA==,type:str]
    HOMEPAGE_VAR_LIDARR_KEY: ENC[AES256_GCM,data:BYt9Bkc1vnh+zL8=,iv:4sIaq3CuH2fdY6+5YSEGFMusdhVXO8YAbWDV8Raf/ic=,tag:JSA/wcQQDF6d3TwiWcSsRQ==,type:str]
    HOMEPAGE_VAR_BAZARR_KEY: ENC[AES256_GCM,data:QUjphvMOLWUu6/w=,iv:O/BG2qCSfCceZSzFt/zCcsBaxaF76FVPns+mjBZ6+LM=,tag:bXWZp68HfiMLYNWrbPSwiA==,type:str]
    HOMEPAGE_VAR_AGH_USERNAME: ENC[AES256_GCM,data:jkyArkZHR19BYck=,iv:aPrpcwRAMHcqBQFQYcsmxoXQwc844MhmEaY8ngHZJjs=,tag:TmqNW6EGe/7H9+UVDfcSFg==,type:str]
    HOMEPAGE_VAR_AGH_PASSWORD: ENC[AES256_GCM,data:sLi3+vyy9ugMeeU=,iv:e7XyUDUq3Qkwl0nTpa3h7nbLL9iVePgovOU1RH+ZZLI=,tag:sea73S48fVGqDPTIdxoNaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180mw9nde354qyrklgcylwdn42ql657j6vcpdud5gqpeyp7e9v4xsrdns9t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMUNPZ0tUbUpLUHQ3OHVE
            WEdjZ0VYVFhpWUFFd3lHMTNiYkd4WmltczNBCnFuM0VVWlViRzdvVGEwM3NpZU9C
            WUt4dHhEcXNZaFQwQ3haMWZrNWtHN28KLS0tIGt3a2xtQTNYNEVSTXlxMzRXMThk
            cVN3aDRPKzR6Rkd1dlZwbk4zYUdwY00KofGkpTQzhVqIid1I9VcbZYmWqz1dMA7i
            Sd8rtv+zp7rMC94sJkzTHY2mpOwBz72FlbN9jj6pzYii/uvmUE7xfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-22T15:38:48Z"
    mac: ENC[AES256_GCM,data:SA2dr02rTCt20p/haEAK+MwI0HdVu9kQCVOdM4PyYqc7KLYMsOqoldcs9Slf8obmgKQwjln39qkIETgEKLFR3YEjTozAYZ35+etIzzpbakPUpNumQDE9PGgT/WmuEl87hyKfKvO54WorUIk3U7LBx7eYxIDxn3imGxVahciDX9g=,iv:8oUUAITzFeYMQKV8FNwZ20cEUDTVC3WDB2AGQqhmDes=,tag:YRSFzb0vkQdmFTe8+srBLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
