---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-home-ops
spec:
  interval: 30m
  chart:
    spec:
      chart: actions-runner-controller-charts/gha-runner-scale-set
      version: 0.11.0
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
      interval: 30m
  driftDetection:
    mode: enabled
  values:
    runnerScaleSetName: arc-runner-set-home-ops

    githubConfigUrl: https://github.com/kireque/home-ops

    minRunners: 0
    maxRunners: 2

    containerMode:
      type: kubernetes
      kubernetesModeWorkVolumeClaim:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ceph-block
        resources:
          requests:
            storage: 2Gi

    controllerServiceAccount:
      name: actions-runner-controller-gha-rs-controller
      namespace: actions-runner-system

    listenerTemplate:
      metadata:
        labels:
          app.kubernetes.io/name: arc-runner-set-home-ops-listener
      spec:
        containers: []

    template:
      metadata:
        labels:
          app.kubernetes.io/name: arc-runner-set-home-ops-runner
      spec:
        automountServiceAccountToken: true
        containers:
          - name: runner
            image: ghcr.io/onedr0p/actions-runner:2.322.0
            command: ["/home/runner/run.sh"]
            env:
              - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                value: "false"
              - name: NODE_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
            volumeMounts:
              - mountPath: /var/run/secrets/talos.dev
                name: talos
                readOnly: true
        securityContext:
          fsGroup: 123
        serviceAccountName: actions-runner
        volumes:
          - name: talos
            secret:
              secretName: actions-runner

  valuesFrom:
    - kind: Secret
      name: actions-runner-controller-auth
      valuesKey: github_app_id
      targetPath: githubConfigSecret.github_app_id
    - kind: Secret
      name: actions-runner-controller-auth
      valuesKey: github_app_installation_id
      targetPath: githubConfigSecret.github_app_installation_id
    - kind: Secret
      name: actions-runner-controller-auth
      valuesKey: github_app_private_key
      targetPath: githubConfigSecret.github_app_private_key
