---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tautulli
spec:
  components:
    - ../../../../components/kopiur/adopt-static
    - ../../../../components/kopiur/backup
    - ../../../../components/nfs-scaler
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/media/tautulli/app
  postBuild:
    substitute:
      APP: tautulli
      KOPIUR_VOLUMENAME: pvc-20089049-f4e7-47ef-8cfa-cef89bd745f0
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
