---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mailbackup-secrets
  namespace: scripts
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mailbackup-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        "2022": |
          [retriever]
          type = SimpleIMAPSSLRetriever
          server = imap.fastmail.com
          mailboxes = ("Archive/2022",)
          username = {{ .fastmail_username }}
          password = {{ .fastmail_mailbackup }}
          [destination]
          type = Maildir
          path = /data/2022/
          [options]
          verbose = 2
          read_all = false
          delivered_to = false
          received = false
        "2023": |
          [retriever]
          type = SimpleIMAPSSLRetriever
          server = imap.fastmail.com
          mailboxes = ("Archive/2023",)
          username = {{ .fastmail_username }}
          password = {{ .fastmail_mailbackup }}
          [destination]
          type = Maildir
          path = /data/2023/
          [options]
          verbose = 2
          read_all = false
          delivered_to = false
          received = false
  dataFrom:
    - extract:
        key: Fastmail
      rewrite:
        - regexp:
            source: "(.*)"
            target: "fastmail_$1"
