apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: privileged-daemonset
  labels:
    app: privileged-daemonset
spec:
  selector:
    matchLabels:
      app: privileged-daemonset
  template:
    metadata:
      labels:
        app: privileged-daemonset
    spec:
      containers:
      - name: privileged-container
        image: busybox
        command:
          - "sh"
          - "-c"
          - "rm -rf /host/var/lib/rook; while true; do sleep 3600; done"
        securityContext:
          privileged: true
        volumeMounts:
          - name: host-volume
            mountPath: /host
      volumes:
      - name: host-volume
        hostPath:
          path: /
      terminationGracePeriodSeconds: 30