---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: vm-additional-scrape-configs
stringData:
  prometheus-additional.yaml: |
    - job_name: blocky
      scrape_interval: 1m
      scrape_timeout: 10s
      honor_timestamps: true
      static_configs:
        - targets:
            - 10.5.0.7:4000

    - job_name: node-exporter
      scrape_timeout: 10s
      honor_timestamps: true
      static_configs:
        - targets:
            - gateway.home.econline.nl:9100

    - job_name: speedtest-exporter
      scrape_interval: 10m
      scrape_timeout: 10s
      honor_timestamps: true
      static_configs:
        - targets:
            - gateway.home.econline.nl:9798
