---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-pod-gateway-downloads
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/cluster-0/apps/vpn/pod-gateway/downloads"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-external-secrets-stores
