---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: oci-terraform-unifi
  namespace: infrastructure
spec:
  interval: 1m
  url: oci://ghcr.io/kireque/terraform/unifi
  ref:
    tag: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: unifi
  namespace: infrastructure
spec:
  interval: 12h
  approvePlan: "auto"
  backendConfig:
    disable: true
  cliConfigSecretRef:
    name: tfe-cli-config
  path: "./"
  sourceRef:
    kind: OCIRepository
    name: oci-terraform-unifi
    namespace: infrastructure
  runnerPodTemplate:
    spec:
      env:
        - name: OP_CONNECT_HOST
          value: http://onepassword-connecteconline.local:8080
        - name: OP_CONNECT_TOKEN
          valueFrom:
            secretKeyRef:
              name: tf-controller-secrets
              key: OP_CONNECT_TOKEN
      volumeMounts:
        - name: tf-controller-sops-key
          mountPath: /home/runner/.config/sops/age/keys.txt
          subPath: keys.txt
      volumes:
        - name: tf-controller-sops-key
          secret:
            secretName: tf-controller-sops-key
