---
clusterName: ${clusterName}

talosVersion: v1.4.6
kubernetesVersion: v1.27.3
endpoint: "https://${clusterName}.${domainName}:6443"

cniConfig:
  name: none

additionalApiServerCertSans:
  - ${clusterEndpointIP}

additionalMachineCertSans:
  - ${clusterEndpointIP}
  - ${clusterName}.${domainName}

nodes:
  - hostname: talos-01
    disableSearchDomain: true
    ipAddress: 192.168.0.21
    controlPlane: true
    installDiskSelector:
      busPath: /pci0000:00/0000:00:17.0/ata3/host2/target2:0:0/2:0:0:0/
    networkInterfaces:
      - interface: eth0
        dhcp: true

  - hostname: talos-02
    disableSearchDomain: true
    ipAddress: 192.168.0.22
    controlPlane: true
    installDiskSelector:
      busPath: /pci0000:00/0000:00:17.0/ata3/host2/target2:0:0/2:0:0:0/
    networkInterfaces:
      - interface: eth0
        dhcp: true

  - hostname: talos-03
    disableSearchDomain: true
    ipAddress: 192.168.0.23
    controlPlane: true
    installDiskSelector:
      busPath: /pci0000:00/0000:00:17.0/ata3/host2/target2:0:0/2:0:0:0/
    networkInterfaces:
      - interface: eth0
        dhcp: true

controlPlane:
  patches:
    - |-
      cluster:
        allowSchedulingOnMasters: true
        proxy:
          disabled: true
        etcd:
          advertisedSubnets:
            - 192.168.0.0/23
        extraManifests:
          - https://raw.githubusercontent.com/bjw-s/home-ops/main/infrastructure/talos/cluster-0/integrations/cni/cilium.yaml
          - https://raw.githubusercontent.com/bjw-s/home-ops/main/infrastructure/talos/cluster-0/integrations/kubelet-csr-approver/kubelet-csr-approver.yaml

    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl

    - |-
      machine:
        files:
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            content: |
              [plugins]
                [plugins."io.containerd.grpc.v1.cri"]
                  enable_unprivileged_ports = true
                  enable_unprivileged_icmp = true
        kubelet:
          extraArgs:
            feature-gates: CronJobTimeZone=true,GracefulNodeShutdown=true,NewVolumeManagerReconstruction=false
            rotate-server-certificates: "true"
          extraConfig:
            maxPods: 150
          nodeIP:
            validSubnets:
                - 192.168.0.0/23
        network:
          extraHostEntries:
            - ip: ${clusterEndpointIP}
              aliases:
                - ${clusterName}.${domainName}
        install:
          extensions:
            - image: ghcr.io/siderolabs/i915-ucode:20230625
            - image: ghcr.io/siderolabs/intel-ucode:20230613
        sysctls:
          fs.inotify.max_user_watches: "1048576"
          fs.inotify.max_user_instances: "8192"
        time:
          disabled: false
          servers:
            - ${router}