---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-alertmanager
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/monitoring/alertmanager/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-rook-ceph-cluster