---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-metrics-server
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/kube-system/metrics-server/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true