---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      type: statefulset

    image:
      repository: ghcr.io/esphome/esphome
      tag: 2023.10.3@sha256:4217b2b0853b21c2442d8af55c03e9a7fbd1f90c8689b1fd42a67938af0bf963

    podAnnotations:
      secret.reloader.stakater.com/reload: esphome-secrets,esphome-deploykey
      k8s.v1.cni.cncf.io/networks: |
        [{
          "name":"multus-iot",
          "namespace": "networking",
          "ips": ["192.168.10.201/24"]
        }]

    service:
      main:
        ports:
          http:
            port: 6052

    ingress:
      main:
        enabled: true
        ingressClassName: "internal-nginx"
        hosts:
          - host: &host "esphome.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      secrets:
        enabled: true
        type: secret
        name: esphome-secrets
        mountPath: /config/secrets.yaml
        subPath: secrets.yaml
      esphome-cache:
        enabled: true
        type: emptyDir
        mountPath: /config/.esphome
      deploy-key:
        enabled: true
        type: secret
        name: esphome-deploykey
        defaultMode: 256
        subPath:
          - path: id_ed25519
            mountPath: /root/.ssh/id_ed25519

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    resources:
      requests:
        cpu: 5m
        memory: 1374M
      limits:
        memory: 2048M

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: ceph-block
