---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  filter:
    name: Lint - Filter
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.changed_files }}
    steps:
      - name: Get Changed Files
        id: changed-files
        uses: bjw-s-labs/action-changed-files@a9a36fb08ce06db9b02fbd8026cc2c0945eb9841 # v0.6.0
        with:
          patterns: |
            **/*.yaml
            **/*.yml

  yamllint:
    if: ${{ needs.filter.outputs.changed-files != '[]' }}
    needs: filter
    name: Lint - yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install yamllint
        run: pipx install yamllint==1.38.0

      - name: Run yamllint
        env:
          FILES: ${{ needs.filter.outputs.changed-files }}
        run: echo "$FILES" | jq -r '.[]' | xargs -r yamllint -c .yamllint.yaml

  actionlint:
    if: ${{ needs.filter.outputs.changed-files != '[]' }}
    needs: filter
    name: Lint - actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install actionlint
        run: |
          bash <(curl -fsSL https://raw.githubusercontent.com/rhysd/actionlint/v1.7.12/scripts/download-actionlint.bash) 1.7.12 "$RUNNER_TEMP"
          echo "$RUNNER_TEMP" >> "$GITHUB_PATH"

      - name: Run actionlint
        env:
          FILES: ${{ needs.filter.outputs.changed-files }}
        run: echo "$FILES" | jq -r '.[] | select(startswith(".github/workflows/"))' | xargs -r actionlint

  success:
    if: ${{ !cancelled() }}
    needs:
      - yamllint
      - actionlint
    name: Lint - Success
    runs-on: ubuntu-latest
    steps:
      - name: Any jobs failed?
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: All jobs passed or skipped?
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: echo "All jobs passed or skipped" && echo "${{ toJSON(needs.*.result) }}"
