---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            .github/workflows/**/*.yml
            .github/workflows/**/*.yaml

      - name: Install actionlint
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Add actionlint problem matcher
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          curl "https://raw.githubusercontent.com/rhysd/actionlint/main/.github/actionlint-matcher.json" -o actionlint-matcher.json
          echo "::add-matcher::actionlint-matcher.json"

      - name: Run actionlint
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          ./actionlint -color --config-file .ci/actionlint/actionlint.yml ${{ steps.changed-files.outputs.all_changed_files }}

  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **.yml
            **.yaml

      - name: Install yamllint
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          pip install yamllint

      - name: Run yamllint
        if: steps.changed-files.outputs.any_changed == 'true'
        run: yamllint --config-file .ci/yamllint/.yamllint.yaml --format github ${{ steps.changed-files.outputs.all_changed_files }}

  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **.md

      - name: Run markdownlint-cli2
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ./.github/actions/lint-markdownlint-cli2
        with:
          markdownlint_config: .ci/markdownlint/.markdownlint.yaml
          file_pattern: ${{ steps.changed-files.outputs.all_changed_files }}

  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Run prettier
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ./.github/actions/lint-prettier
        with:
          prettier_ignore: .ci/prettier/.prettierignore
          prettier_config: .ci/prettier/.prettierrc.yaml
          file_pattern: ${{ steps.changed-files.outputs.all_changed_files }}

  lint_success:
    needs:
      - actionlint
      - prettier
      - yamllint
      - markdownlint
    if: |
      always()
    name: Lint successful
    runs-on: ubuntu-latest
    steps:
      - name: Check job status
        if: >-
          ${{
              (
                contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
              )
          }}
        run: exit 1