---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Meta - Labeler

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.KIREQUE_APP_ID }}
          private_key: ${{ secrets.KIREQUE_APP_PRIVATE_KEY }}

      - name: Labeler
        uses: actions/labeler@v5
        with:
          repo-token: "${{ steps.generate-token.outputs.token }}"
          configuration-path: .github/labeler.yaml
