---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: scrypted
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: kireque
        namespace: flux-system

  values:
    controller:
      type: statefulset

    image:
      repository: ghcr.io/koush/scrypted
      tag: 18-jammy-full-v0.39.4

    podAnnotations:
      k8s.v1.cni.cncf.io/networks: |
        [{
          "name":"multus-iot",
          "namespace": "network",
          "ips": ["10.1.3.153/24"]
        }]

    service:
      main:
        ports:
          http:
            port: 11080

    ingress:
      main:
        enabled: true
        ingressClassName: "internal-nginx"
        hosts:
          - host: &host "scryptedeconline.local"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    nodeSelector:
      google.feature.node.kubernetes.io/coral: "true"
      intel.feature.node.kubernetes.io/gpu: "true"

    persistence:
      cache:
        enabled: true
        mountPath: /.cache
        type: emptyDir
      cache-npm:
        enabled: true
        mountPath: /.npm
        type: emptyDir
      dev-bus-usb:
        enabled: true
        type: hostPath
        hostPath: /dev/bus/usb
        hostPathType: Directory
        mountPath: /dev/bus/usb
      sys-bus-usb:
        enabled: true
        type: hostPath
        hostPath: /sys/bus/usb
        hostPathType: Directory
        mountPath: /sys/bus/usb
      recs:
        enabled: true
        mountPath: /recs
        path: /volume1/Media/IPCams/scrypted
        server: synology.econline.local
        type: nfs

    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 136m
        memory: 1024Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 8192Mi

    securityContext:
      privileged: true

    volumeClaimTemplates:
      - name: config
        mountPath: /server/volume
        accessMode: ReadWriteOnce
        size: 2Gi
        storageClass: ceph-block
